DIRS?= --library=../math_libs --library=../Qbricks

ide_qbricks_c:
	why3 ide $(DIRS) qbricks_c.mlw

ide_qbricks:
	why3 ide $(DIRS) qbricks.mlw

ide_derived_circuits_c:
	why3 ide $(DIRS) derived_circuits_c.mlw

ide_pps:
	why3 ide $(DIRS) pps.mlw

ide_qdata:
	why3 ide $(DIRS) ../math_libs/qdata.mlw

ide_binary:
	why3 ide $(DIRS) ../math_libs/binary.mlw