DIRS?= --library=../math_libs --library=../Qbricks --library=../Case_studies

ide_deutsch-jozsa:
	why3 ide $(DIRS) deutsch-jozsa.mlw

ide_dj_oracle:
	why3 ide $(DIRS) dj_oracle.mlw

ide_grover:
	why3 ide $(DIRS) grover.mlw

ide_modular_adder:
	why3 ide $(DIRS) modular_adder.mlw

ide_modular_multiplier:
	why3 ide $(DIRS) modular_multiplier.mlw

ide_qft:
	why3 ide $(DIRS) qft.mlw

ide_qpe:
	why3 ide $(DIRS) qpe.mlw

ide_shor_circuit:
	why3 ide $(DIRS) shor_circuit.mlw

ide_shor:
	why3 ide $(DIRS) shor.mlw


