(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require int.Abs.
Require int.EuclideanDivision.
Require map.Map.

Axiom t : Type.
Parameter t_WhyType : WhyType t.
Existing Instance t_WhyType.

Parameter tzero: t.

Parameter tone: t.

Parameter infix_asdt: t -> t -> t.

Parameter infix_pldt: t -> t -> t.

Parameter infix_lseqdt: t -> t -> Prop.

Parameter prefix_mn: t -> t.

Axiom Assoc :
  forall (x:t) (y:t) (z:t),
  ((infix_pldt (infix_pldt x y) z) = (infix_pldt x (infix_pldt y z))).

Axiom Unit_def_l : forall (x:t), ((infix_pldt tzero x) = x).

Axiom Unit_def_r : forall (x:t), ((infix_pldt x tzero) = x).

Axiom Inv_def_l : forall (x:t), ((infix_pldt (prefix_mn x) x) = tzero).

Axiom Inv_def_r : forall (x:t), ((infix_pldt x (prefix_mn x)) = tzero).

Axiom Comm : forall (x:t) (y:t), ((infix_pldt x y) = (infix_pldt y x)).

Axiom Assoc1 :
  forall (x:t) (y:t) (z:t),
  ((infix_asdt (infix_asdt x y) z) = (infix_asdt x (infix_asdt y z))).

Axiom Mul_distr_l :
  forall (x:t) (y:t) (z:t),
  ((infix_asdt x (infix_pldt y z)) =
   (infix_pldt (infix_asdt x y) (infix_asdt x z))).

Axiom Mul_distr_r :
  forall (x:t) (y:t) (z:t),
  ((infix_asdt (infix_pldt y z) x) =
   (infix_pldt (infix_asdt y x) (infix_asdt z x))).

Axiom Comm1 : forall (x:t) (y:t), ((infix_asdt x y) = (infix_asdt y x)).

Axiom Unitary : forall (x:t), ((infix_asdt tone x) = x).

Axiom NonTrivialRing : ~ (tzero = tone).

Axiom Refl : forall (x:t), infix_lseqdt x x.

Axiom Trans :
  forall (x:t) (y:t) (z:t), (infix_lseqdt x y) -> (infix_lseqdt y z) ->
  infix_lseqdt x z.

Axiom Antisymm :
  forall (x:t) (y:t), (infix_lseqdt x y) -> (infix_lseqdt y x) -> (x = y).

(* Why3 assumption *)
Definition infix_mndt (x:t) (y:t) : t := infix_pldt x (prefix_mn y).

(* Why3 assumption *)
Definition infix_lsdt (i:t) (j:t) : Prop := (infix_lseqdt i j) /\ ~ (i = j).

Parameter requal: t -> t -> bool.

Axiom requal_spec : forall (a:t) (b:t), ((requal a b) = true) <-> (a = b).

Axiom ZeroLessOne : infix_lsdt tzero tone.

Axiom absorbing_zero : forall (i:t), ((infix_asdt i tzero) = tzero).

(* Why3 assumption *)
Definition comparable (a:t) (b:t) : Prop :=
  (infix_lseqdt a b) \/ (infix_lseqdt b a).

Axiom Transitive_comparable :
  forall (x:t) (y:t) (z:t), (comparable x y) -> (comparable y z) ->
  comparable x z.

Axiom Unitary_comparable :
  forall (x:t) (y:t), (comparable x y) ->
  (comparable x tzero) /\ (comparable x tone).

Axiom CompatStrictOrderAdd :
  forall (x:t) (y:t) (z:t), (infix_lsdt x y) -> (comparable x z) ->
  infix_lsdt (infix_pldt x z) (infix_pldt y z).

Axiom notZeroAdd :
  forall (x:t) (y:t), ~ (x = tzero) -> ~ ((infix_pldt x y) = y).

Axiom CompatOrderMult :
  forall (x:t) (y:t) (z:t), (infix_lsdt x y) -> (infix_lsdt tzero z) ->
  infix_lsdt (infix_asdt x z) (infix_asdt y z).

Axiom compatStrictOrderMultComm :
  forall (x:t) (y:t) (z:t), (infix_lsdt x y) -> (infix_lsdt tzero z) ->
  infix_lsdt (infix_asdt z x) (infix_asdt z y).

Axiom compatOrderMult :
  forall (x:t) (y:t) (z:t), (infix_lseqdt x y) -> (infix_lseqdt tzero z) ->
  infix_lseqdt (infix_asdt x z) (infix_asdt y z).

Axiom compatOrderMultComm :
  forall (x:t) (y:t) (z:t), (infix_lseqdt x y) -> (infix_lseqdt tzero z) ->
  infix_lseqdt (infix_asdt z x) (infix_asdt z y).

Parameter inv: t -> t.

Axiom Inverse :
  forall (x:t), ~ (x = tzero) -> ((infix_asdt x (inv x)) = tone).

(* Why3 assumption *)
Definition infix_sldt (x:t) (y:t) : t := infix_asdt x (inv y).

Axiom add_div :
  forall (x:t) (y:t) (z:t), ~ (z = tzero) ->
  ((infix_sldt (infix_pldt x y) z) =
   (infix_pldt (infix_sldt x z) (infix_sldt y z))).

Axiom sub_div :
  forall (x:t) (y:t) (z:t), ~ (z = tzero) ->
  ((infix_sldt (infix_mndt x y) z) =
   (infix_mndt (infix_sldt x z) (infix_sldt y z))).

Axiom neg_div :
  forall (x:t) (y:t), ~ (y = tzero) ->
  ((infix_sldt (prefix_mn x) y) = (prefix_mn (infix_sldt x y))).

Axiom assoc_mul_div :
  forall (x:t) (y:t) (z:t), ~ (z = tzero) ->
  ((infix_sldt (infix_asdt x y) z) = (infix_asdt x (infix_sldt y z))).

Axiom assoc_div_mul :
  forall (x:t) (y:t) (z:t), (~ (y = tzero) /\ ~ (z = tzero)) ->
  ((infix_sldt (infix_sldt x y) z) = (infix_sldt x (infix_asdt y z))).

Axiom assoc_div_div :
  forall (x:t) (y:t) (z:t), (~ (y = tzero) /\ ~ (z = tzero)) ->
  ((infix_sldt x (infix_sldt y z)) = (infix_sldt (infix_asdt x z) y)).

Axiom inv_mult :
  forall (x:t) (y:t), ~ (x = tzero) -> ~ (y = tzero) ->
  ((infix_asdt (infix_sldt tone x) (infix_sldt tone y)) =
   (infix_sldt tone (infix_asdt x y))).

Axiom set : forall (a:Type), Type.
Parameter set_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (set a).
Existing Instance set_WhyType.

Parameter mem: forall {a:Type} {a_WT:WhyType a}, a -> (set a) -> Prop.

Parameter infix_eqeq:
  forall {a:Type} {a_WT:WhyType a}, (set a) -> (set a) -> Prop.

Axiom infix_eqeq_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a),
  (infix_eqeq s1 s2) <-> forall (x:a), (mem x s1) <-> (mem x s2).

Axiom extensionality :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a), (infix_eqeq s1 s2) -> (s1 = s2).

Parameter subset:
  forall {a:Type} {a_WT:WhyType a}, (set a) -> (set a) -> Prop.

Axiom subset_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a),
  (subset s1 s2) <-> forall (x:a), (mem x s1) -> mem x s2.

Axiom subset_refl :
  forall {a:Type} {a_WT:WhyType a}, forall (s:set a), subset s s.

Axiom subset_trans :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a) (s3:set a), (subset s1 s2) ->
  (subset s2 s3) -> subset s1 s3.

Parameter is_empty: forall {a:Type} {a_WT:WhyType a}, (set a) -> Prop.

Axiom is_empty_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), (is_empty s) <-> forall (x:a), ~ (mem x s).

Parameter empty: forall {a:Type} {a_WT:WhyType a}, set a.

Axiom empty_def : forall {a:Type} {a_WT:WhyType a}, is_empty (empty : set a).

Parameter add: forall {a:Type} {a_WT:WhyType a}, a -> (set a) -> set a.

Axiom add_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (s:set a), forall (y:a),
  (mem y (add x s)) <-> ((y = x) \/ (mem y s)).

Parameter remove: forall {a:Type} {a_WT:WhyType a}, a -> (set a) -> set a.

Axiom remove_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (s:set a), forall (y:a),
  (mem y (remove x s)) <-> (~ (y = x) /\ (mem y s)).

Axiom add_remove :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (s:set a), (mem x s) -> ((add x (remove x s)) = s).

Axiom remove_add :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (s:set a), ((remove x (add x s)) = (remove x s)).

Axiom subset_remove :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (s:set a), subset (remove x s) s.

Parameter union:
  forall {a:Type} {a_WT:WhyType a}, (set a) -> (set a) -> set a.

Axiom union_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a), forall (x:a),
  (mem x (union s1 s2)) <-> ((mem x s1) \/ (mem x s2)).

Parameter inter:
  forall {a:Type} {a_WT:WhyType a}, (set a) -> (set a) -> set a.

Axiom inter_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a), forall (x:a),
  (mem x (inter s1 s2)) <-> ((mem x s1) /\ (mem x s2)).

Parameter diff:
  forall {a:Type} {a_WT:WhyType a}, (set a) -> (set a) -> set a.

Axiom diff_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a), forall (x:a),
  (mem x (diff s1 s2)) <-> ((mem x s1) /\ ~ (mem x s2)).

Axiom subset_diff :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a), subset (diff s1 s2) s1.

Parameter choose: forall {a:Type} {a_WT:WhyType a}, (set a) -> a.

Axiom choose_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), ~ (is_empty s) -> mem (choose s) s.

Parameter cardinal: forall {a:Type} {a_WT:WhyType a}, (set a) -> Z.

Axiom cardinal_nonneg :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), (0%Z <= (cardinal s))%Z.

Axiom cardinal_empty :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), ((cardinal s) = 0%Z) <-> (is_empty s).

Axiom cardinal_add :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a), forall (s:set a), ~ (mem x s) ->
  ((cardinal (add x s)) = (1%Z + (cardinal s))%Z).

Axiom cardinal_remove :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a), forall (s:set a), (mem x s) ->
  ((cardinal s) = (1%Z + (cardinal (remove x s)))%Z).

Axiom cardinal_subset :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a), (subset s1 s2) ->
  ((cardinal s1) <= (cardinal s2))%Z.

Axiom subset_eq :
  forall {a:Type} {a_WT:WhyType a},
  forall (s1:set a) (s2:set a), (subset s1 s2) ->
  ((cardinal s1) = (cardinal s2)) -> infix_eqeq s1 s2.

Axiom cardinal1 :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), ((cardinal s) = 1%Z) -> forall (x:a), (mem x s) ->
  (x = (choose s)).

Parameter op: forall {im:Type} {im_WT:WhyType im}, im -> im -> im.

Parameter po: forall {im:Type} {im_WT:WhyType im}, im -> im -> im.

Parameter inver: forall {im:Type} {im_WT:WhyType im}, im -> im.

Parameter filter:
  forall {a:Type} {a_WT:WhyType a}, (a -> bool) -> (set a) -> set a.

Axiom filter_def :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> bool) (u:set a), forall (x:a),
  (mem x (filter p u)) <-> (((p x) = true) /\ (mem x u)).

Axiom filter_cardinal :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:a -> bool) (u:set a), ((cardinal (filter p u)) <= (cardinal u))%Z.

Parameter map:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (a -> b) ->
  (set a) -> set b.

Axiom map_def1 :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (u:set a), forall (y:b),
  (mem y (map f u)) <-> exists x:a, (mem x u) /\ (y = (f x)).

Axiom map_def2 :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (u:set a), forall (x:a), (mem x u) -> mem (f x) (map f u).

Axiom map_cardinal :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (u:set a), ((cardinal (map f u)) <= (cardinal u))%Z.

Axiom assert_equal :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:a) (b:a), (a1 = b) -> (a1 = b).

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Axiom union_exchange :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), ~ (is_empty s') ->
  ((union (add (choose s') s) (remove (choose s') s')) = (union s s')).

Axiom inter_empty :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), (is_empty s) -> is_empty (inter s s').

Axiom inter_empty_comm :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), (is_empty s') -> is_empty (inter s s').

Axiom union_empty :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), (is_empty s) -> ((union s s') = s').

Axiom union_comm :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), (is_empty s') -> ((union s s') = s).

Axiom union_empty_comm :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), (is_empty s') -> ((union s s') = s).

Axiom set_subset :
  forall {a:Type} {a_WT:WhyType a},
  forall (s':set a) (s:set a), (forall (e:a), (mem e s') -> mem e s) ->
  subset s' s.

Axiom set_empty :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), (forall (e:a), ~ (mem e s)) ->
  (s = (empty : set a)) /\ (is_empty s).

Axiom set_equal :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), (forall (e:a), (mem e s) -> mem e s') ->
  (forall (e:a), (mem e s') -> mem e s) -> (s = s').

Axiom get_empty :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), (s = (empty : set a)) ->
  (forall (e:a), ~ (mem e s)) /\ (is_empty s).

Axiom get_non_empty :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), ~ (is_empty s) -> exists e:a, mem e s.

Axiom set_non_empty :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), (exists e:a, mem e s) ->
  ~ (is_empty s) /\ (0%Z < (cardinal s))%Z.

Axiom union_add :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a) (x:a), ~ (mem x s') ->
  ((union s (add x s')) = (add x (union s s'))).

Axiom union_add_comm :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a) (x:a), ~ (mem x s') ->
  ((add x (union s s')) = (union s (add x s'))).

Axiom remove_add1 :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (x:a), ~ (mem x s) -> ((remove x (add x s)) = s).

Axiom add_remove1 :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (x:a), (mem x s) -> ((add x (remove x s)) = s).

(* Why3 assumption *)
Definition injective {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    (s:set a) (f:a -> b) : Prop :=
  forall (a1:a) (b1:a), ~ (a1 = b1) -> ~ ((f a1) = (f b1)).

Axiom map_choose :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s:set a), forall (f:a -> b), ((choose (map f s)) = (f (choose s))).

Axiom set_map_mem :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (s:set a) (b1:b),
  (exists a1:a, (mem a1 s) /\ (b1 = (f a1))) -> mem b1 (map f s).

Axiom map_add :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (s:set a) (x:a), ~ (mem x s) ->
  ((map f (add x s)) = (add (f x) (map f s))).

Axiom map_eq :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (g:a -> b) (s:set a),
  (forall (e:a), (mem e s) -> ((f e) = (g e))) -> ((map f s) = (map g s)).

Axiom set_map_mem_el :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (s:set a) (b1:b) (a1:a), (mem a1 s) -> (b1 = (f a1)) ->
  mem b1 (map f s).

Axiom map_antec :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (s:set a) (b1:b), (mem b1 (map f s)) ->
  exists a1:a, (mem a1 s) /\ (b1 = (f a1)).

Axiom map_antec_gen :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (s:set a), forall (b1:b), (mem b1 (map f s)) ->
  exists a1:a, (mem a1 s) /\ (b1 = (f a1)).

Axiom map_remove_choose :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s:set a) (f:a -> b), (injective s f) ->
  ((map f (remove (choose s) s)) = (remove (choose (map f s)) (map f s))).

Parameter right_injections:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, a -> (set b) ->
  set (a* b)%type.

Axiom right_injections_def :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (a1:a) (s:set b),
  ((is_empty s) -> ((right_injections a1 s) = (empty : set (a* b)%type))) /\
  (~ (is_empty s) ->
   ((right_injections a1 s) =
    (add (a1, choose s) (right_injections a1 (remove (choose s) s))))).

Axiom right_injections_spec :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (a1:a) (s:set b),
  ((cardinal (right_injections a1 s)) = (cardinal s)) /\
  ((forall (a':a), forall (b1:b),
    (mem (a', b1) (right_injections a1 s)) <-> ((a' = a1) /\ (mem b1 s))) /\
   ((right_injections a1 s) = (map ((fun (a2:a) (b1:b) => (a2, b1)) a1) s))).

Parameter left_injections:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (set a) -> b ->
  set (a* b)%type.

Axiom left_injections_def :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s:set a) (b1:b),
  ((is_empty s) -> ((left_injections s b1) = (empty : set (a* b)%type))) /\
  (~ (is_empty s) ->
   ((left_injections s b1) =
    (add (choose s, b1) (left_injections (remove (choose s) s) b1)))).

Axiom left_injections_spec :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s:set a) (b1:b),
  (forall (a1:a), forall (b':b),
   (mem (a1, b') (left_injections s b1)) <-> ((mem a1 s) /\ (b' = b1))) /\
  (((cardinal (left_injections s b1)) = (cardinal s)) /\
   ((left_injections s b1) = (map ((fun (b2:b) (a1:a) => (a1, b2)) b1) s))).

Axiom right_injections_l :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (a1:a) (s:set b),
  ((cardinal (right_injections a1 s)) = (cardinal s)) /\
  ((forall (a':a), forall (b1:b),
    (mem (a', b1) (right_injections a1 s)) <-> ((a' = a1) /\ (mem b1 s))) /\
   ((right_injections a1 s) = (map ((fun (a2:a) (b1:b) => (a2, b1)) a1) s))).

Axiom left_injections_l :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s:set a) (b1:b),
  (forall (a1:a), forall (b':b),
   (mem (a1, b') (left_injections s b1)) <-> ((mem a1 s) /\ (b' = b1))) /\
  (((cardinal (left_injections s b1)) = (cardinal s)) /\
   ((left_injections s b1) = (map ((fun (b2:b) (a1:a) => (a1, b2)) b1) s))).

Axiom disjoint_injections :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s:set a) (b1:b) (c:b), ~ (b1 = c) ->
  (is_empty (inter (right_injections b1 s) (right_injections c s))) /\
  (is_empty (inter (left_injections s b1) (left_injections s c))).

Axiom induction :
  forall {a:Type} {a_WT:WhyType a},
  forall (p:(set a) -> bool) (t1:set a),
  (forall (s:set a), (is_empty s) -> ((p s) = true)) ->
  (forall (s:set a), ((p s) = true) -> forall (t2:a), ~ (mem t2 s) ->
   ((p (add t2 s)) = true)) ->
  ((p t1) = true).

Axiom cardinal_sum :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a),
  ((cardinal (union s s')) =
   (((cardinal s) + (cardinal s'))%Z - (cardinal (inter s s')))%Z).

Axiom cardinal_sum_empty_inter :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (s':set a), ((inter s s') = (empty : set a)) ->
  ((cardinal (union s s')) = ((cardinal s) + (cardinal s'))%Z).

Parameter cartesian_product:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (set a) ->
  (set b) -> set (a* b)%type.

Axiom cartesian_product_spec :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set b),
  ((cardinal (cartesian_product s1 s2)) = ((cardinal s1) * (cardinal s2))%Z) /\
  ((forall (a1:a), forall (b1:b),
    (mem (a1, b1) (cartesian_product s1 s2)) <-> ((mem a1 s1) /\ (mem b1 s2))) /\
   forall (o:(a* b)%type),
   (mem o (cartesian_product s1 s2)) <->
   match o with
   | (a1, b1) => (mem a1 s1) /\ (mem b1 s2)
   end).

(* Why3 assumption *)
Definition commute {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    (o:(a* b)%type) : (b* a)%type :=
  match o with
  | (a1, b1) => (b1, a1)
  end.

Axiom commute_inj :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (a1:a) (a':a) (b1:b) (b':b), ((a1 = a') -> ~ (b1 = b')) ->
  ~ ((commute (a1, b1)) = (commute (a', b'))).

Axiom commute_inj_gen :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set b),
  injective (cartesian_product s1 s2) (fun (y0:(a* b)%type) => (commute y0)).

(* Why3 assumption *)
Definition commute_product {a:Type} {a_WT:WhyType a}
    {b:Type} {b_WT:WhyType b} (s1:set a) (s2:set b) : set (b* a)%type :=
  map (fun (y0:(a* b)%type) => (commute y0)) (cartesian_product s1 s2).

Axiom commute_product_spec :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set b),
  ((commute_product s1 s2) = (cartesian_product s2 s1)).

(* Why3 assumption *)
Definition commute_product_el {a:Type} {a_WT:WhyType a}
    {b:Type} {b_WT:WhyType b} (s1:set a) (s2:set b) : set (b* a)%type :=
  map (fun (y0:(a* b)%type) => (commute y0)) (cartesian_product s1 s2).

Axiom commute_product_el_spec :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set b), forall (o:(a* b)%type),
  match o with
  | (a1, b1) =>
      ((mem o (cartesian_product s1 s2)) <-> ((mem a1 s1) /\ (mem b1 s2))) /\
      (((mem a1 s1) /\ (mem b1 s2)) <->
       (mem (b1, a1) (commute_product_el s1 s2)))
  end.

Axiom cartesian_product_union :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set b) (s3:set b),
  ((cartesian_product s1 (union s2 s3)) =
   (union (cartesian_product s1 s2) (cartesian_product s1 s3))).

Axiom cartesian_union_product :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set a) (s3:set b),
  ((cartesian_product (union s1 s2) s3) =
   (union (cartesian_product s1 s3) (cartesian_product s2 s3))).

Axiom cartesian_product_cardone_r :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set b), ((cardinal s1) = 1%Z) ->
  (infix_eqeq (cartesian_product s1 s2) (right_injections (choose s1) s2)) /\
  (infix_eqeq (cartesian_product s1 s2)
   (map ((fun (e:a) (e2:b) => (e, e2)) (choose s1)) s2)).

Axiom cartesian_product_cardone_l :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s1:set a) (s2:set b), ((cardinal s2) = 1%Z) ->
  (infix_eqeq (cartesian_product s1 s2) (left_injections s1 (choose s2))) /\
  (infix_eqeq (cartesian_product s1 s2)
   (map ((fun (e:b) (e1:a) => (e1, e)) (choose s2)) s1)).

(* Why3 assumption *)
Definition op_neutral_left {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (neutral:im) : Prop :=
  forall (e:im), (((op1 neutral) e) = e).

(* Why3 assumption *)
Definition op_neutral_right {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (neutral:im) : Prop :=
  forall (e:im), (((op1 e) neutral) = e).

(* Why3 assumption *)
Definition op_assoc {im:Type} {im_WT:WhyType im} (op1:im -> im -> im) : Prop :=
  forall (a:im) (b:im) (c:im),
  (((op1 ((op1 a) b)) c) = ((op1 a) ((op1 b) c))).

(* Why3 assumption *)
Definition op_neutral_left_comm {im:Type} {im_WT:WhyType im}
    (op1:im -> im -> im) (neutral:im) : Prop :=
  forall (a:im), (forall (b:im), (((op1 a) b) = b)) -> (a = neutral).

(* Why3 assumption *)
Definition commut {im:Type} {im_WT:WhyType im} (op1:im -> im -> im) : Prop :=
  forall (a:im) (b:im), (((op1 a) b) = ((op1 b) a)).

(* Why3 assumption *)
Definition assoc {im:Type} {im_WT:WhyType im} (op1:im -> im -> im) : Prop :=
  forall (a:im) (b:im) (c:im),
  (((op1 ((op1 a) b)) c) = ((op1 a) ((op1 b) c))).

(* Why3 assumption *)
Definition opposite_n {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (po1:im -> im -> im) (neutral:im) : Prop :=
  forall (a:im), (((po1 a) a) = neutral).

(* Why3 assumption *)
Definition inverse {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (po1:im -> im -> im) (inver1:im -> im) : Prop :=
  forall (a:im) (b:im), (((po1 a) b) = ((op1 a) (inver1 b))).

(* Why3 assumption *)
Definition opposite {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (po1:im -> im -> im) : Prop :=
  forall (a:im) (b:im), (((op1 ((po1 a) b)) b) = a).

(* Why3 assumption *)
Definition opposite_com {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (po1:im -> im -> im) : Prop :=
  forall (a:im) (b:im), (((po1 ((op1 a) b)) b) = a).

Axiom refl :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (a:im) (b:im), (commut op1) ->
  (((op1 a) b) = ((op1 b) a)).

(* Why3 assumption *)
Definition neutral {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (neut:im) : Prop :=
  (op_neutral_left op1 neut) /\
  ((op_neutral_right op1 neut) /\ (op_assoc op1)).

Axiom set_neutral :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (neut:im), (op_neutral_left op1 neut) ->
  (op_neutral_right op1 neut) -> (op_assoc op1) -> neutral op1 neut.

(* Why3 assumption *)
Definition has_neutral {im:Type} {im_WT:WhyType im} (op1:im -> im -> im) :
    Prop :=
  exists e:im, neutral op1 e.

(* Why3 assumption *)
Definition iterates {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (neutral1:im) : Prop :=
  (op_neutral_left op1 neutral1) /\
  ((op_neutral_right op1 neutral1) /\ ((op_assoc op1) /\ (commut op1))).

(* Why3 assumption *)
Definition iterable {im:Type} {im_WT:WhyType im} (op1:im -> im -> im) : Prop :=
  exists e:im, iterates op1 e.

Parameter neutral_elt:
  forall {im:Type} {im_WT:WhyType im}, (im -> im -> im) -> im.

Axiom neutral_elt_spec :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im), forall (e:im),
  (neutral op1 e) <-> ((neutral_elt op1) = e).

(* Why3 assumption *)
Definition inverse_tuple {im:Type} {im_WT:WhyType im} (op1:im -> im -> im)
    (po1:im -> im -> im) (neutral1:im) : Prop :=
  (opposite_n op1 po1 neutral1) /\
  ((opposite op1 po1) /\ (opposite_com op1 po1)).

Parameter iterate:
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  (im -> im -> im) -> (set a) -> (a -> im) -> im.

Axiom Iterate_def_empty :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im), forall (s:set a), forall (f:a -> im),
  (is_empty s) -> ((iterate op1 (empty : set a) f) = (neutral_elt op1)).

Axiom Iterate_add :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im), forall (s:set a), forall (f:a -> im),
  forall (x:a), ~ (mem x s) ->
  ((iterate op1 (add x s) f) = ((op1 (f x)) (iterate op1 s f))).

Axiom minus_zero :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (po1:im -> im -> im) (a:im), (iterable op1) ->
  (inverse_tuple op1 po1 (neutral_elt op1)) ->
  (((po1 a) (neutral_elt op1)) = a).

Axiom unic :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (po1:im -> im -> im) (a:im) (b:im) (c:im),
  (iterable op1) -> (((op1 a) b) = ((op1 a) c)) ->
  (inverse_tuple op1 po1 (neutral_elt op1)) -> (b = c).

Axiom substract_comm :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (po1:im -> im -> im) (a:im) (b:im) (c:im),
  (iterable op1) -> (inverse_tuple op1 po1 (neutral_elt op1)) ->
  (((po1 ((op1 a) b)) a) = b) /\
  ((((po1 ((op1 b) a)) a) = b) /\
   ((((po1 a) ((po1 b) c)) = ((op1 ((po1 a) b)) c)) /\
    (((po1 ((op1 a) b)) c) = ((op1 a) ((po1 b) c))))).

Parameter int_iterate:
  forall {im:Type} {im_WT:WhyType im}, (im -> im -> im) -> (Z -> im) -> 
  Z -> Z -> im.

Axiom int_iterate_def :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (j:Z),
  ((j <= i)%Z -> ((int_iterate op1 f i j) = (neutral_elt op1))) /\
  (~ (j <= i)%Z ->
   ((int_iterate op1 f i j) =
    ((op1 (f i)) (int_iterate op1 f (i + 1%Z)%Z j)))).

Axiom int_iterate_spec :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (j:Z), (j <= i)%Z ->
  ((int_iterate op1 f i j) = (neutral_elt op1)).

Parameter int_int_iterate:
  forall {im:Type} {im_WT:WhyType im}, (im -> im -> im) -> (Z -> Z -> im) ->
  Z -> Z -> Z -> Z -> im.

Axiom int_int_iterate_def :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> Z -> im) (i:Z) (j:Z) (k:Z) (l:Z),
  ((j <= i)%Z -> ((int_int_iterate op1 f i j k l) = (neutral_elt op1))) /\
  (~ (j <= i)%Z ->
   ((int_int_iterate op1 f i j k l) =
    ((op1 (int_iterate op1 ((fun (y0:Z -> im) (y1:Z) => (y0 y1)) (f i)) k l))
     (int_int_iterate op1 f (i + 1%Z)%Z j k l)))).

Parameter element: forall {a:Type} {a_WT:WhyType a}, (set a) -> a.

Axiom element_def :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), ((cardinal s) = 1%Z) -> ((element s) = (choose s)).

Axiom cardone :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (a1:a), (forall (b:a), (mem b s) <-> (b = a1)) ->
  (0%Z < (cardinal s))%Z -> ((cardinal s) = 1%Z) /\ ((element s) = a1).

Axiom set_cardone :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a), (0%Z < (cardinal s))%Z ->
  (exists a1:a, forall (b:a), (mem b s) <-> (b = a1)) -> ((cardinal s) = 1%Z).

(* Why3 assumption *)
Definition p_injective {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    (f:a -> b) (s:set a) : Prop :=
  forall (e:a) (e':a), (mem e s) -> (mem e' s) -> ~ (e = e') ->
  ~ ((f e) = (f e')).

(* Why3 assumption *)
Definition p_injective_in {a:Type} {a_WT:WhyType a} (f:a -> a) (s:set a)
    (s':set a) : Prop :=
  forall (e:a), (mem e s) ->
  (mem (f e) s') /\
  forall (e1:a) (e':a), (mem e1 s) -> (mem e' s) -> ~ (e1 = e') ->
  ~ ((f e1) = (f e')).

Axiom set_injective :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (s:set a),
  (forall (e:a) (e':a), (mem e s) -> (mem e' s) -> ~ (e = e') ->
   ~ ((f e) = (f e'))) ->
  p_injective f s.

Axiom get_injective :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:a -> b) (s:set a), (p_injective f s) -> forall (e:a) (e':a),
  (mem e s) -> (mem e' s) -> ~ (e = e') -> ~ ((f e) = (f e')).

Axiom set_injective_in :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a) (s':set a),
  (forall (e:a), (mem e s) -> mem (f e) s') ->
  (forall (e:a) (e':a), (mem e s) -> (mem e' s) -> ~ (e = e') ->
   ~ ((f e) = (f e'))) ->
  p_injective f s.

Axiom get_injective_in :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a) (s':set a), (p_injective_in f s s') ->
  (forall (e:a), (mem e s) -> mem (f e) s') /\
  forall (e:a) (e':a), (mem e s) -> (mem e' s) -> ~ (e = e') ->
  ~ ((f e) = (f e')).

(* Why3 assumption *)
Definition p_surjective {a:Type} {a_WT:WhyType a} (f:a -> a) (s:set a)
    (s':set a) : Prop :=
  forall (e':a), (mem e' s') -> exists e:a, (mem e s) /\ ((f e) = e').

Axiom set_surjective :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a) (s':set a),
  (forall (e':a), (mem e' s') -> exists e:a, (mem e s) /\ ((f e) = e')) ->
  p_surjective f s s'.

Axiom get_surjective :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a) (s':set a), (p_surjective f s s') ->
  forall (e':a), (mem e' s') -> exists e:a, (mem e s) /\ ((f e) = e').

(* Why3 assumption *)
Definition range {a:Type} {a_WT:WhyType a} (f:a -> a) (s:set a) : Prop :=
  forall (e:a), (mem e s) -> mem (f e) s.

Axiom set_range :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a), (forall (e:a), (mem e s) -> mem (f e) s) ->
  range f s.

Axiom get_range :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a), (range f s) -> forall (e:a), (mem e s) ->
  mem (f e) s.

(* Why3 assumption *)
Definition p_bijective {a:Type} {a_WT:WhyType a} (f:a -> a) (s:set a)
    (s':set a) : Prop :=
  (p_injective_in f s s') /\ (p_surjective f s s').

Axiom set_bijective :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a) (s':set a),
  (forall (e:a), (mem e s) -> mem (f e) s') ->
  (forall (e:a) (e':a), (mem e s) -> (mem e' s) -> ~ (e = e') ->
   ~ ((f e) = (f e'))) ->
  (forall (e':a), (mem e' s') -> exists e:a, (mem e s) /\ ((f e) = e')) ->
  p_bijective f s s'.

Axiom get_bijective :
  forall {a:Type} {a_WT:WhyType a},
  forall (f:a -> a) (s:set a) (s':set a), (p_bijective f s s') ->
  (forall (e:a), (mem e s) -> mem (f e) s') /\
  ((forall (e:a) (e':a), (mem e s) -> (mem e' s) -> ~ (e = e') ->
    ~ ((f e) = (f e'))) /\
   forall (e':a), (mem e' s') -> exists e:a, (mem e s) /\ ((f e) = e')).

Axiom iterate_empty :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im), (is_empty s) ->
  ((iterate op1 s t1) = (neutral_elt op1)).

Axiom iterate_add :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (f:a -> im) (x:a), ~ (mem x s) ->
  ((iterate op1 (add x s) f) = ((op1 (f x)) (iterate op1 s f))).

Axiom iterate_remove :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (f:a -> im) (x:a), (iterable op1) ->
  (inverse_tuple op1 (fun (y0:im) (y1:im) => (po y0 y1)) (neutral_elt op1)) ->
  (mem x s) -> ((iterate op1 (remove x s) f) = (po (iterate op1 s f) (f x))).

Axiom iterate_def_choose :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (f:a -> im), (iterable op1) ->
  ~ (is_empty s) ->
  ((iterate op1 s f) =
   ((op1 (f (choose s))) (iterate op1 (remove (choose s) s) f))).

Axiom choose_any :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (f:a -> im) (t1:a), (iterable op1) ->
  (mem t1 s) ->
  ((iterate op1 s f) = ((op1 (f t1)) (iterate op1 (remove t1 s) f))).

Axiom iterate_comp_iterate :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s1:set a) (f:a -> im) (g:a -> im),
  (iterable op1) -> (assoc op1) ->
  ((iterate op1 s1
    ((((fun (op2:im -> im -> im) (f1:a -> im) (g1:a -> im) (k:a) =>
        ((op2 (f1 k)) (g1 k)))
       op1)
      f)
     g))
   =
   ((op1 (iterate op1 s1 ((fun (f1:a -> im) (k:a) => (f1 k)) f)))
    (iterate op1 s1 ((fun (g1:a -> im) (k:a) => (g1 k)) g)))).

Axiom iterate_comp_iterate_com :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s1:set a) (f:a -> im) (g:a -> im),
  (iterable op1) ->
  (((op1 (iterate op1 s1 ((fun (f1:a -> im) (k:a) => (f1 k)) f)))
    (iterate op1 s1 ((fun (g1:a -> im) (k:a) => (g1 k)) g)))
   =
   (iterate op1 s1
    ((((fun (op2:im -> im -> im) (f1:a -> im) (g1:a -> im) (k:a) =>
        ((op2 (f1 k)) (g1 k)))
       op1)
      f)
     g))).

Axiom iterate_transitivity :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (po1:im -> im -> im) (s1:set a) (s2:set a)
    (f:a -> im),
  (iterable op1) -> (inverse_tuple op1 po1 (neutral_elt op1)) ->
  ((iterate op1 (union s1 s2) f) =
   ((po1 ((op1 (iterate op1 s1 f)) (iterate op1 s2 f)))
    (iterate op1 (inter s1 s2) f))).

Axiom iterate_disjoint_transitivity :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s1:set a) (s2:set a) (t1:a -> im),
  (iterable op1) -> ((inter s1 s2) = (empty : set a)) ->
  ((iterate op1 (union s1 s2) t1) =
   ((op1 (iterate op1 s1 t1)) (iterate op1 s2 t1))).

Axiom iterate_eq :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (f:a -> im) (g:a -> im),
  (forall (x:a), (mem x s) -> ((f x) = (g x))) ->
  ((iterate op1 s f) = (iterate op1 s g)).

Axiom iterate_map :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set b) (f:b -> a) (t1:a -> im),
  (iterable op1) -> (p_injective f s) ->
  ((iterate op1 (map f s) t1) =
   (iterate op1 s
    (((fun (f1:b -> a) (t2:a -> im) (b1:b) => (t2 (f1 b1))) f) t1))).

Axiom iterate_eq_func :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (f1:a -> im) (f2:a -> im),
  (iterable op1) -> (p_injective f1 s) -> (p_injective f2 s) ->
  ((map f1 s) = (map f2 s)) -> ((iterate op1 s f1) = (iterate op1 s f2)).

Axiom to_set_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (e:a),
  ((cardinal (add e (empty : set a))) = 1%Z) /\
  forall (b:a), (mem b (add e (empty : set a))) -> (b = e).

Parameter to_fset: Z -> Z -> set Z.

Axiom to_fset_spec :
  forall (i:Z) (j:Z),
  ((i < j)%Z -> ((cardinal (to_fset i j)) = (j - i)%Z)) /\
  (((j <= i)%Z -> is_empty (to_fset i j)) /\
   forall (k:Z), (mem k (to_fset i j)) <-> ((i <= k)%Z /\ (k < j)%Z)).

Axiom choose_to_fset :
  forall (i:Z) (j:Z), (i <= j)%Z -> ((choose (to_fset i j)) = i).

Axiom to_fset_unit_ext :
  forall (i:Z) (j:Z), (i < j)%Z ->
  ((to_fset i j) = (add i (to_fset (i + 1%Z)%Z j))).

Axiom to_fset_ext :
  forall (i:Z) (i':Z) (j:Z), ((i <= i')%Z /\ (i' <= j)%Z) ->
  ((to_fset i j) = (union (to_fset i i') (to_fset i' j))).

Axiom int_iterate_def_empty :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (j:Z), (j <= i)%Z ->
  ((int_iterate op1 f i j) = (neutral_elt op1)).

Axiom int_iterate_def_plus_one :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (j:Z), (i < j)%Z ->
  ((int_iterate op1 f i j) = ((op1 (f i)) (int_iterate op1 f (i + 1%Z)%Z j))).

Axiom int_iterate_def_plus_one_com :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (j:Z), (i < j)%Z ->
  (((op1 (f i)) (int_iterate op1 f (i + 1%Z)%Z j)) = (int_iterate op1 f i j)).

Axiom int_iterate_to_iterate :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (j:Z),
  ((int_iterate op1 f i j) = (iterate op1 (to_fset i j) f)).

Axiom int_iterate_right_extension :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (j:Z), (assoc op1) ->
  (i < j)%Z ->
  ((int_iterate op1 f i j) =
   ((op1 (int_iterate op1 f i (j - 1%Z)%Z)) (f (j - 1%Z)%Z))).

Axiom int_iterate_transitivity :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (i:Z) (k:Z) (j:Z), (assoc op1) ->
  (op_neutral_left op1 (neutral_elt op1)) -> ((i <= k)%Z /\ (k <= j)%Z) ->
  ((int_iterate op1 f i j) =
   ((op1 (int_iterate op1 f i k)) (int_iterate op1 f k j))).

Axiom int_iterate_comp_iterate :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (g:Z -> im) (i:Z) (j:Z),
  (assoc op1) -> (op_neutral_right op1 (neutral_elt op1)) -> (commut op1) ->
  ((int_iterate op1
    ((((fun (op2:im -> im -> im) (f1:Z -> im) (g1:Z -> im) (k:Z) =>
        ((op2 (f1 k)) (g1 k)))
       op1)
      f)
     g)
    i j)
   = ((op1 (int_iterate op1 f i j)) (int_iterate op1 g i j))).

Axiom int_iterate_attr_no_f :
  forall {im1:Type} {im1_WT:WhyType im1} {im2:Type} {im2_WT:WhyType im2},
  forall (op1:im1 -> im1 -> im1) (op2:im2 -> im2 -> im2) (t1:Z -> im1)
    (t2:Z -> im2) (f:im1 -> im2) (i:Z) (j:Z),
  (forall (x:Z), forall (y:im1),
   (((op2 (t2 x)) (f y)) = (f ((op1 (t1 x)) y)))) ->
  ((f (neutral_elt op1)) = (neutral_elt op2)) -> (assoc op1) ->
  (assoc op2) -> (forall (i1:Z), ((f (t1 i1)) = (t2 i1))) ->
  ((int_iterate op2 t2 i j) = (f (int_iterate op1 t1 i j))).

Axiom int_iterate_attr :
  forall {im1:Type} {im1_WT:WhyType im1} {im2:Type} {im2_WT:WhyType im2},
  forall (op1:im1 -> im1 -> im1) (op2:im2 -> im2 -> im2) (t1:Z -> im1)
    (f:im1 -> im2) (i:Z) (j:Z),
  (forall (x:Z), forall (y:im1),
   (((op2 (f (t1 x))) (f y)) = (f ((op1 (t1 x)) y)))) ->
  ((f (neutral_elt op1)) = (neutral_elt op2)) -> (assoc op1) ->
  (assoc op2) ->
  ((int_iterate op2
    (((fun (t2:Z -> im1) (f1:im1 -> im2) (e:Z) => (f1 (t2 e))) t1) f) i j)
   = (f (int_iterate op1 t1 i j))).

Axiom int_iterate_attr_comm :
  forall {im1:Type} {im1_WT:WhyType im1} {im2:Type} {im2_WT:WhyType im2},
  forall (op1:im1 -> im1 -> im1) (op2:im2 -> im2 -> im2) (t1:Z -> im1)
    (f:im1 -> im2) (i:Z) (j:Z),
  (forall (x:Z), forall (y:im1),
   (((op2 (f (t1 x))) (f y)) = (f ((op1 (t1 x)) y)))) ->
  ((f (neutral_elt op1)) = (neutral_elt op2)) -> (assoc op1) ->
  (assoc op2) ->
  ((f (int_iterate op1 t1 i j)) =
   (int_iterate op2
    (((fun (t2:Z -> im1) (f1:im1 -> im2) (e:Z) => (f1 (t2 e))) t1) f) i j)).

Axiom int_iterate_eq :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (g:Z -> im) (i:Z) (j:Z),
  (forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> ((f k) = (g k))) ->
  ((int_iterate op1 f i j) = (int_iterate op1 g i j)).

Axiom int_iterate_left_right :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f:Z -> im) (l:Z) (k:Z) (h:Z), (assoc op1) ->
  (commut op1) -> ((l <= k)%Z /\ (k <= h)%Z) ->
  ((int_iterate op1 f l k) =
   (int_iterate op1
    ((((fun (f1:Z -> im) (l1:Z) (h1:Z) (a:Z) =>
        (f1 ((h1 - (a + 1%Z)%Z)%Z + l1)%Z))
       f)
      l)
     h)
    ((h - k)%Z + l)%Z h)).

Axiom int_iterate_eq_func :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (i:Z) (j:Z) (f1:Z -> im) (f2:Z -> im),
  (iterable op1) -> (p_injective f1 (to_fset i j)) ->
  (p_injective f2 (to_fset i j)) ->
  ((map f1 (to_fset i j)) = (map f2 (to_fset i j))) ->
  ((int_iterate op1 f1 i j) = (int_iterate op1 f2 i j)).

Axiom int_iterate_map :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set b) (f:b -> a) (t1:a -> im),
  (iterable op1) -> (p_injective f s) ->
  ((iterate op1 (map f s) t1) =
   (iterate op1 s
    (((fun (f1:b -> a) (t2:a -> im) (b1:b) => (t2 (f1 b1))) f) t1))).

Parameter f:
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  (im -> im -> im) -> (a -> im) -> a -> bool.

Axiom f_def :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (t1:a -> im) (e:a),
  (((((f : (im -> im -> im) -> (a -> im) -> a -> bool) op1) t1) e) = true) <->
  ~ (neutral op1 (t1 e)).

(* Why3 assumption *)
Definition nonn_part {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im}
    (op1:im -> im -> im) (s:set a) (t1:a -> im) : set a :=
  filter (((f : (im -> im -> im) -> (a -> im) -> a -> bool) op1) t1) s.

Axiom nonn_part_spec :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im), forall (e:a),
  (mem e (nonn_part op1 s t1)) <-> ((mem e s) /\ ~ (neutral op1 (t1 e))).

Parameter f1:
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  (im -> im -> im) -> (a -> im) -> a -> bool.

Axiom f_def1 :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (t1:a -> im) (e:a),
  (((((f1 : (im -> im -> im) -> (a -> im) -> a -> bool) op1) t1) e) = true) <->
  (neutral op1 (t1 e)).

(* Why3 assumption *)
Definition n_part {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im}
    (op1:im -> im -> im) (s:set a) (t1:a -> im) : set a :=
  filter (((f1 : (im -> im -> im) -> (a -> im) -> a -> bool) op1) t1) s.

Axiom n_part_spec :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im), forall (e:a),
  (mem e (n_part op1 s t1)) <-> ((mem e s) /\ (neutral op1 (t1 e))).

Axiom nullity_partition :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im),
  (s = (union (nonn_part op1 s t1) (n_part op1 s t1))) /\
  ((inter (nonn_part op1 s t1) (n_part op1 s t1)) = (empty : set a)).

Axiom iterate_neutral :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im), (iterable op1) ->
  (forall (a1:a), (mem a1 s) -> ((t1 a1) = (neutral_elt op1))) ->
  ((iterate op1 s t1) = (neutral_elt op1)).

Axiom iterate_nullity_partition :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im), (iterable op1) ->
  ((iterate op1 s t1) = (iterate op1 (nonn_part op1 s t1) t1)).

Axiom iterate_cardone :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im), (iterable op1) ->
  ((cardinal s) = 1%Z) -> ((iterate op1 s t1) = (t1 (element s))).

Axiom iterate_cardzero :
  forall {a:Type} {a_WT:WhyType a} {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set a) (t1:a -> im), (iterable op1) ->
  ((cardinal s) = 0%Z) -> ((iterate op1 s t1) = (neutral_elt op1)).

(* Why3 assumption *)
Definition couple {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    {im:Type} {im_WT:WhyType im} (f2:a -> b -> im) (o:(a* b)%type) : im :=
  match o with
  | (a1, b1) => (f2 a1) b1
  end.

Axiom null_product :
  forall (a:t) (b:t), ((infix_asdt a b) = tzero) ->
  (a = tzero) \/ (b = tzero).

(* Why3 assumption *)
Definition sum {a:Type} {a_WT:WhyType a} (s:set a) (t1:a -> t) : t :=
  iterate (fun (y0:t) (y1:t) => (infix_pldt y0 y1)) s t1.

Axiom sum_iter : iterates (fun (y0:t) (y1:t) => (infix_pldt y0 y1)) tzero.

Axiom sum_iter__ : iterable (fun (y0:t) (y1:t) => (infix_pldt y0 y1)).

Axiom map_sum_eq :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (s:set b) (f2:b -> a) (t1:a -> t), (p_injective f2 s) ->
  ((sum (map f2 s) t1) =
   (sum s (((fun (f3:b -> a) (t2:a -> t) (b1:b) => (t2 (f3 b1))) f2) t1))).

Axiom sum_iter_ :
  (opposite_n (fun (y0:t) (y1:t) => (infix_pldt y0 y1))
   (fun (y0:t) (y1:t) => (infix_mndt y0 y1)) tzero) /\
  ((opposite (fun (y0:t) (y1:t) => (infix_pldt y0 y1))
    (fun (y0:t) (y1:t) => (infix_mndt y0 y1))) /\
   ((opposite_com (fun (y0:t) (y1:t) => (infix_pldt y0 y1))
     (fun (y0:t) (y1:t) => (infix_mndt y0 y1))) /\
    (inverse_tuple (fun (y0:t) (y1:t) => (infix_pldt y0 y1))
     (fun (y0:t) (y1:t) => (infix_mndt y0 y1)) tzero))).

Axiom neutral_zero :
  ((neutral_elt (fun (y0:t) (y1:t) => (infix_pldt y0 y1))) = tzero).

Axiom sum_eq :
  forall {a:Type} {a_WT:WhyType a},
  forall (s:set a) (f2:a -> t) (g:a -> t),
  (forall (x:a), (mem x s) -> ((f2 x) = (g x))) -> ((sum s f2) = (sum s g)).

(* Why3 assumption *)
Definition ind_sum (f2:Z -> t) (i:Z) (j:Z) : t :=
  int_iterate (fun (y0:t) (y1:t) => (infix_pldt y0 y1)) f2 i j.

Axiom ind_sum_comp :
  forall (f2:Z -> t) (g:Z -> t) (i:Z) (j:Z),
  ((ind_sum
    (((fun (f3:Z -> t) (g1:Z -> t) (k:Z) => (infix_pldt (f3 k) (g1 k))) f2)
     g)
    i j)
   = (infix_pldt (ind_sum f2 i j) (ind_sum g i j))).

Axiom ind_sum_eq :
  forall (f2:Z -> t) (g:Z -> t) (i:Z) (j:Z),
  (forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> ((f2 k) = (g k))) ->
  ((ind_sum f2 i j) = (ind_sum g i j)).

(* Why3 assumption *)
Definition product {a:Type} {a_WT:WhyType a} (s:set a) (t1:a -> t) : t :=
  iterate (fun (y0:t) (y1:t) => (infix_asdt y0 y1)) s t1.

Axiom product_iter :
  (op_neutral_left (fun (y0:t) (y1:t) => (infix_asdt y0 y1)) tone) /\
  (((op_neutral_right (fun (y0:t) (y1:t) => (infix_asdt y0 y1)) tone) /\
    (op_assoc (fun (y0:t) (y1:t) => (infix_asdt y0 y1)))) /\
   ((commut (fun (y0:t) (y1:t) => (infix_asdt y0 y1))) /\
    (iterates (fun (y0:t) (y1:t) => (infix_asdt y0 y1)) tone))).

Axiom product_iter_ : iterable (fun (y0:t) (y1:t) => (infix_asdt y0 y1)).

Axiom neutral_one :
  ((neutral_elt (fun (y0:t) (y1:t) => (infix_asdt y0 y1))) = tone).

(* Why3 assumption *)
Definition ind_product (f2:Z -> t) (i:Z) (j:Z) : t :=
  int_iterate (fun (y0:t) (y1:t) => (infix_asdt y0 y1)) f2 i j.

Axiom ind_product_eq :
  forall (f2:Z -> t) (g:Z -> t) (i:Z) (j:Z),
  (forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> ((f2 k) = (g k))) ->
  ((ind_product f2 i j) = (ind_product g i j)).

Axiom ind_product_right_extension :
  forall (f2:Z -> t) (i:Z) (j:Z), (i < j)%Z ->
  ((ind_product f2 i j) =
   (infix_asdt (ind_product f2 i (j - 1%Z)%Z) (f2 (j - 1%Z)%Z))).

Axiom ind_product_left_extension :
  forall (f2:Z -> t) (i:Z) (j:Z), (i < j)%Z ->
  ((ind_product f2 i j) = (infix_asdt (f2 i) (ind_product f2 (i + 1%Z)%Z j))).

Axiom ind_product_right_extension_comm :
  forall (f2:Z -> t) (i:Z) (j:Z), (i < j)%Z ->
  ((infix_asdt (ind_product f2 i (j - 1%Z)%Z) (f2 (j - 1%Z)%Z)) =
   (ind_product f2 i j)).

Axiom ind_product_eq_func :
  forall (i:Z) (j:Z) (f11:Z -> t) (f2:Z -> t),
  (p_injective f11 (to_fset i j)) -> (p_injective f2 (to_fset i j)) ->
  ((map f11 (to_fset i j)) = (map f2 (to_fset i j))) ->
  ((ind_product f11 i j) = (ind_product f2 i j)).

(* Why3 assumption *)
Definition antisym {a:Type} {a_WT:WhyType a} (rel:a -> a -> bool) : Prop :=
  forall (a1:a) (b:a), (((rel a1) b) = true) -> (((rel b) a1) = true) ->
  (a1 = b).

(* Why3 assumption *)
Definition transitive {a:Type} {a_WT:WhyType a} (rel:a -> a -> bool) : Prop :=
  forall (a1:a) (b:a) (c:a), (((rel a1) b) = true) -> (((rel b) c) = true) ->
  (((rel a1) c) = true).

(* Why3 assumption *)
Definition reflexive {a:Type} {a_WT:WhyType a} (rel:a -> a -> bool) : Prop :=
  forall (a1:a), (((rel a1) a1) = true).

(* Why3 assumption *)
Definition pre_order {a:Type} {a_WT:WhyType a} (rel:a -> a -> bool) : Prop :=
  (transitive rel) /\ (reflexive rel).

(* Why3 assumption *)
Definition partial_order {a:Type} {a_WT:WhyType a} (rel:a -> a -> bool) :
    Prop :=
  (antisym rel) /\ (pre_order rel).

(* Why3 assumption *)
Definition recip {a:Type} {a_WT:WhyType a} (rrel:a -> a -> bool)
    (rel:a -> a -> bool) : Prop :=
  forall (a1:a) (b:a), (((rrel a1) b) = true) <-> (((rel b) a1) = true).

(* Why3 assumption *)
Definition strict {a:Type} {a_WT:WhyType a} (srel:a -> a -> bool)
    (rel:a -> a -> bool) : Prop :=
  forall (a1:a) (b:a),
  (((srel a1) b) = true) <-> ((((rel a1) b) = true) /\ ~ (a1 = b)).

(* Why3 assumption *)
Definition compat_order_mult {a:Type} {a_WT:WhyType a} (rel:a -> a -> bool)
    (mul:a -> a -> a) (tzero1:a) : Prop :=
  forall (a1:a) (b:a) (c:a), (((rel a1) b) = true) ->
  (((rel tzero1) c) = true) -> (((rel ((mul a1) c)) ((mul b) c)) = true).

Parameter c_iter:
  forall {a:Type} {a_WT:WhyType a}, (a -> a -> a) -> a -> Z -> a.

Axiom c_iter_def :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (t1:a) (i:Z), (0%Z <= i)%Z ->
  ((c_iter op1 t1 i) =
   (int_iterate op1 ((fun (y0:a) (y1:Z) => y0) t1) 0%Z i)).

Axiom c_iter_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (t1:a) (i:Z), (0%Z <= i)%Z ->
  ((c_iter op1 t1 i) =
   (int_iterate op1 ((fun (y0:a) (y1:Z) => y0) t1) 0%Z i)).

Axiom c_iter_transl :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (t1:a) (i:Z) (k:Z), (assoc op1) -> (0%Z <= k)%Z ->
  (0%Z <= i)%Z ->
  ((c_iter op1 t1 i) =
   (int_iterate op1 ((fun (y0:a) (y1:Z) => y0) t1) k (k + i)%Z)).

Axiom c_iter_0 :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a), (has_neutral op1) ->
  ((c_iter op1 x 0%Z) = (neutral_elt op1)).

Axiom c_iter_1 :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a), (has_neutral op1) ->
  ((c_iter op1 x 1%Z) = x).

Axiom c_iter_plus_1_right :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (i:Z), (0%Z <= i)%Z -> (assoc op1) ->
  (has_neutral op1) ->
  ((c_iter op1 x (i + 1%Z)%Z) = ((op1 (c_iter op1 x i)) x)).

Axiom c_iter_plus_1_left :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (i:Z), (0%Z <= i)%Z -> (has_neutral op1) ->
  ((c_iter op1 x (i + 1%Z)%Z) = ((op1 x) (c_iter op1 x i))).

Axiom c_iter_s :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (n:Z), (has_neutral op1) -> (0%Z <= n)%Z ->
  ((c_iter op1 x (n + 1%Z)%Z) = ((op1 x) (c_iter op1 x n))) /\
  ((c_iter op1 x (n + 1%Z)%Z) = ((op1 (c_iter op1 x n)) x)).

Axiom c_iter_s_alt :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (n:Z), (has_neutral op1) -> (0%Z < n)%Z ->
  ((c_iter op1 x n) = ((op1 (c_iter op1 x (n - 1%Z)%Z)) x)) /\
  ((c_iter op1 x n) = ((op1 x) (c_iter op1 x (n - 1%Z)%Z))).

Axiom c_iter_sum :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (n:Z) (m:Z), (has_neutral op1) ->
  (0%Z <= n)%Z -> (0%Z <= m)%Z ->
  ((c_iter op1 x (n + m)%Z) = ((op1 (c_iter op1 x n)) (c_iter op1 x m))).

Axiom c_iter_mult :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (n:Z) (m:Z), (has_neutral op1) ->
  (0%Z <= n)%Z -> (0%Z <= m)%Z ->
  ((c_iter op1 x (n * m)%Z) = (c_iter op1 (c_iter op1 x n) m)).

Axiom c_iter_op_comm1 :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (y:a) (n:Z), (commut op1) -> (0%Z <= n)%Z ->
  (((op1 (c_iter op1 x n)) y) = ((op1 y) (c_iter op1 x n))).

Axiom c_iter_op_comm2 :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (y:a) (n:Z), (iterable op1) ->
  (0%Z <= n)%Z ->
  ((c_iter op1 ((op1 x) y) n) = ((op1 (c_iter op1 x n)) (c_iter op1 y n))).

Axiom positive_diff : forall (n:Z) (m:Z), (n < m)%Z -> (0%Z < (m - n)%Z)%Z.

Axiom init_c_iter :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (k:a) (tone1:a), (neutral op1 tone1) ->
  ((c_iter op1 k 0%Z) = tone1) /\ ((c_iter op1 k 2%Z) = ((op1 k) k)).

Axiom positive_c_iter :
  forall {a:Type} {a_WT:WhyType a},
  forall (rel:a -> a -> bool) (srel:a -> a -> bool) (op1:a -> a -> a)
    (tone1:a) (tzero1:a) (k:a) (n:Z),
  (compat_order_mult rel op1 tzero1) -> (partial_order rel) ->
  (((rel tone1) k) = true) -> (((srel tzero1) tone1) = true) ->
  (strict srel rel) -> (neutral op1 tone1) -> (0%Z <= n)%Z ->
  (((rel tone1) (c_iter op1 k n)) = true) /\
  ((((srel tzero1) (c_iter op1 k n)) = true) /\
   (((rel (c_iter op1 k n)) (c_iter op1 k (n + 1%Z)%Z)) = true)).

Axiom strict_positive_c_iter :
  forall {a:Type} {a_WT:WhyType a},
  forall (rel:a -> a -> bool) (srel:a -> a -> bool) (op1:a -> a -> a)
    (tone1:a) (tzero1:a) (k:a) (n:Z),
  (compat_order_mult rel op1 tzero1) ->
  (compat_order_mult srel op1 tzero1) -> (((srel tzero1) tone1) = true) ->
  (partial_order rel) -> (neutral op1 tone1) -> (((srel tone1) k) = true) ->
  (strict srel rel) -> (0%Z < n)%Z ->
  (((srel tone1) (c_iter op1 k n)) = true) /\
  ((((srel (c_iter op1 k (n - 1%Z)%Z)) (c_iter op1 k n)) = true) /\
   (((srel (c_iter op1 k n)) (c_iter op1 k (n + 1%Z)%Z)) = true)).

Axiom growing_c_iter :
  forall {a:Type} {a_WT:WhyType a},
  forall (rel:a -> a -> bool) (srel:a -> a -> bool) (op1:a -> a -> a)
    (tone1:a) (tzero1:a) (k:a) (m:Z) (n:Z),
  (compat_order_mult rel op1 tzero1) -> (((srel tzero1) tone1) = true) ->
  (compat_order_mult srel op1 tzero1) -> (partial_order rel) ->
  (neutral op1 tone1) -> (((srel tone1) k) = true) -> (strict srel rel) ->
  (((rel tone1) k) = true) -> ((0%Z <= m)%Z /\ (m <= n)%Z) ->
  (((rel (c_iter op1 k m)) (c_iter op1 k n)) = true).

Axiom strict_growing_c_iter :
  forall {a:Type} {a_WT:WhyType a},
  forall (rel:a -> a -> bool) (srel:a -> a -> bool) (op1:a -> a -> a)
    (tone1:a) (tzero1:a) (k:a) (m:Z) (n:Z),
  (compat_order_mult rel op1 tzero1) ->
  (compat_order_mult srel op1 tzero1) -> (((srel tzero1) tone1) = true) ->
  (partial_order rel) -> (neutral op1 tone1) -> (((srel tone1) k) = true) ->
  (strict srel rel) -> (((srel tone1) k) = true) ->
  ((0%Z <= m)%Z /\ (m < n)%Z) ->
  (((srel (c_iter op1 k m)) (c_iter op1 k n)) = true).

Axiom unicity_c_iter :
  forall {a:Type} {a_WT:WhyType a},
  forall (rel:a -> a -> bool) (srel:a -> a -> bool) (op1:a -> a -> a)
    (tone1:a) (tzero1:a) (k:a) (m:Z) (n:Z),
  (compat_order_mult rel op1 tzero1) ->
  (compat_order_mult srel op1 tzero1) -> (((srel tzero1) tone1) = true) ->
  (partial_order rel) -> (neutral op1 tone1) -> (((srel tone1) k) = true) ->
  (strict srel rel) -> (0%Z <= m)%Z -> (0%Z <= n)%Z ->
  ((c_iter op1 k m) = (c_iter op1 k n)) <-> (m = n).

Parameter fir:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (a* b)%type ->
  a.

Parameter sec:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (a* b)%type ->
  b.

Axiom projections :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (o:(a* b)%type), (o = (fir o, sec o)).

(* Why3 assumption *)
Definition matrix (a:Type) := Z -> Z -> a.

Parameter rows: forall {a:Type} {a_WT:WhyType a}, (Z -> Z -> a) -> Z.

Axiom rows_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a), (0%Z < (rows m))%Z.

Parameter columns: forall {a:Type} {a_WT:WhyType a}, (Z -> Z -> a) -> Z.

Axiom columns_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a), (0%Z < (columns m))%Z.

(* Why3 assumption *)
Definition valid_index {a:Type} {a_WT:WhyType a} (a1:Z -> Z -> a) (r:Z)
    (c:Z) : Prop :=
  ((0%Z <= r)%Z /\ (r < (rows a1))%Z) /\
  ((0%Z <= c)%Z /\ (c < (columns a1))%Z).

(* Why3 assumption *)
Definition equal_size {a:Type} {a_WT:WhyType a} (a1:Z -> Z -> a)
    (b:Z -> Z -> a) : Prop :=
  ((rows a1) = (rows b)) /\ ((columns a1) = (columns b)).

Axiom Rows_and_columns :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a), forall (x:a), forall (i:Z) (j:Z),
  (valid_index m i j) ->
  ((rows (map.Map.set m i (map.Map.set (m i) j x))) = (rows m)) /\
  ((columns (map.Map.set m i (map.Map.set (m i) j x))) = (columns m)).

Parameter get:
  forall {a:Type} {a_WT:WhyType a}, (Z -> Z -> a) -> Z -> Z -> a.

Axiom get_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:Z -> Z -> a) (r:Z) (c:Z), (valid_index a1 r c) ->
  ((get a1 r c) = ((a1 r) c)).

Parameter make: forall {a:Type} {a_WT:WhyType a}, Z -> Z -> a -> Z -> Z -> a.

Axiom make_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (r:Z) (c:Z) (v:a), ((0%Z <= r)%Z /\ (0%Z <= c)%Z) ->
  ((rows (make r c v)) = r) /\
  (((columns (make r c v)) = c) /\
   forall (i:Z) (j:Z),
   (((0%Z <= i)%Z /\ (i < r)%Z) /\ ((0%Z <= j)%Z /\ (j < c)%Z)) ->
   ((((make r c v) i) j) = v)).

Parameter set1:
  forall {a:Type} {a_WT:WhyType a}, (Z -> Z -> a) -> Z -> Z -> a ->
  Z -> Z -> a.

Axiom set_def :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:Z -> Z -> a) (r:Z) (c:Z) (v:a), (valid_index a1 r c) ->
  ((set1 a1 r c v) = (map.Map.set a1 r (map.Map.set (a1 r) c v))).

Axiom set_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:Z -> Z -> a) (r:Z) (c:Z) (v:a), (valid_index a1 r c) ->
  ((rows (set1 a1 r c v)) = (rows a1)) /\
  (((columns (set1 a1 r c v)) = (columns a1)) /\
   ((forall (i:Z) (j:Z), (valid_index a1 i j) ->
     (((i = r) /\ (j = c)) -> ((((set1 a1 r c v) i) j) = v)) /\
     (~ ((i = r) /\ (j = c)) -> ((((set1 a1 r c v) i) j) = ((a1 i) j)))) /\
    (((((set1 a1 r c v) r) c) = v) /\
     ((forall (i:Z) (j:Z), (valid_index (set1 a1 r c v) i j) -> ~ (i = r) ->
       ((((set1 a1 r c v) i) j) = ((a1 i) j))) /\
      forall (i:Z) (j:Z), (valid_index (set1 a1 r c v) i j) -> ~ (j = c) ->
      ((((set1 a1 r c v) i) j) = ((a1 i) j)))))).

Parameter make_f:
  forall {a:Type} {a_WT:WhyType a}, Z -> Z -> (Z -> Z -> a) -> Z -> Z -> a.

Axiom make_f_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (r:Z) (c:Z) (f2:Z -> Z -> a), (0%Z <= r)%Z -> (0%Z <= c)%Z ->
  ((rows (make_f r c f2)) = r) /\
  (((columns (make_f r c f2)) = c) /\
   forall (i:Z) (j:Z), (valid_index (make_f r c f2) i j) ->
   ((((make_f r c f2) i) j) = ((f2 i) j))).

Axiom assert_make :
  forall {a:Type} {a_WT:WhyType a},
  forall (r:Z) (c:Z) (f2:Z -> Z -> a) (i:Z) (j:Z),
  ((0%Z <= i)%Z /\ (i < r)%Z) -> ((0%Z <= j)%Z /\ (j < c)%Z) ->
  ((((make_f r c f2) i) j) = ((f2 i) j)).

(* Why3 assumption *)
Definition to_indexes {a:Type} {a_WT:WhyType a} (m:Z -> Z -> a) :
    set (Z* Z)%type :=
  cartesian_product (to_fset 0%Z (rows m)) (to_fset 0%Z (columns m)).

Axiom set_to_indexes_mem :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (i:Z) (j:Z), ((0%Z <= i)%Z /\ (i < (rows m))%Z) ->
  ((0%Z <= j)%Z /\ (j < (columns m))%Z) -> mem (i, j) (to_indexes m).

Axiom get_to_indexes_mem :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (o:(Z* Z)%type), (mem o (to_indexes m)) ->
  ((0%Z <= (fir o))%Z /\ ((fir o) < (rows m))%Z) /\
  ((0%Z <= (sec o))%Z /\ ((sec o) < (columns m))%Z).

Parameter equal:
  forall {a:Type} {a_WT:WhyType a}, (Z -> Z -> a) -> (Z -> Z -> a) -> Prop.

Axiom equal_mat :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (n:Z -> Z -> a),
  (equal m n) <->
  ((((rows m) = (rows n)) /\ ((columns m) = (columns n))) /\
   forall (i:Z) (j:Z), (valid_index m i j) -> (((m i) j) = ((n i) j))).

Axiom equality :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (n:Z -> Z -> a), (equal m n) <-> (m = n).

Axiom mat_equality :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (n:Z -> Z -> a), ((rows m) = (rows n)) ->
  ((columns m) = (columns n)) ->
  (forall (i:Z) (j:Z), (valid_index m i j) -> (((m i) j) = ((n i) j))) ->
  equal m n.

Parameter square: forall {a:Type} {a_WT:WhyType a}, (Z -> Z -> a) -> Prop.

Axiom square_mat :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a), (square m) <-> ((rows m) = (columns m)).

Axiom equal_sym :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (n:Z -> Z -> a), (equal m n) <-> (equal n m).

Axiom equal_rex :
  forall {a:Type} {a_WT:WhyType a}, forall (m:Z -> Z -> a), equal m m.

Axiom equal_trans :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (n:Z -> Z -> a) (o:Z -> Z -> a), (equal m n) ->
  (equal n o) -> equal m o.

Parameter equal_funct:
  forall {a:Type} {a_WT:WhyType a}, (Z -> Z -> Z -> a) ->
  (Z -> Z -> Z -> a) -> Prop.

Axiom equal_mat_funct :
  forall {a:Type} {a_WT:WhyType a},
  forall (f2:Z -> Z -> Z -> a) (g:Z -> Z -> Z -> a), forall (i:Z) (j:Z),
  ((0%Z <= i)%Z /\ (i < j)%Z) ->
  (equal_funct f2 g) <->
  forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> equal (f2 k) (g k).

Axiom set_equal_mat :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (n:Z -> Z -> a), ((rows m) = (rows n)) ->
  ((columns m) = (columns n)) ->
  (forall (i:Z) (j:Z), (valid_index m i j) -> (((m i) j) = ((n i) j))) ->
  (m = n).

Axiom get_equal_mat :
  forall {a:Type} {a_WT:WhyType a},
  forall (m:Z -> Z -> a) (n:Z -> Z -> a), (equal m n) ->
  ((rows m) = (rows n)) /\
  (((columns m) = (columns n)) /\
   forall (i:Z) (j:Z), (valid_index m i j) -> (((m i) j) = ((n i) j))).

Axiom equal_functions :
  forall {a:Type} {a_WT:WhyType a},
  forall (r:Z) (c:Z) (f2:Z -> Z -> a) (g:Z -> Z -> a), (0%Z < r)%Z ->
  (0%Z < c)%Z ->
  (forall (i:Z) (j:Z),
   (((0%Z <= i)%Z /\ (i < r)%Z) /\ ((0%Z <= j)%Z /\ (j < c)%Z)) ->
   (((f2 i) j) = ((g i) j))) ->
  ((make_f r c f2) = (make_f r c g)).

Axiom equal_functions_mat :
  forall {a:Type} {a_WT:WhyType a},
  forall (f2:Z -> Z -> a) (m:Z -> Z -> a),
  (forall (i:Z) (j:Z),
   (((0%Z <= i)%Z /\ (i < (rows m))%Z) /\
    ((0%Z <= j)%Z /\ (j < (columns m))%Z)) ->
   (((f2 i) j) = ((m i) j))) ->
  (m = (make_f (rows m) (columns m) f2)).

Axiom div_plus_one :
  forall (i:Z) (j:Z), (0%Z <= i)%Z -> (0%Z < j)%Z ->
  (((int.EuclideanDivision.div i j) * j)%Z <= i)%Z /\
  (i < (((int.EuclideanDivision.div i j) + 1%Z)%Z * j)%Z)%Z.

Axiom bound_eq :
  forall (i:Z) (j:Z), ((0%Z <= i)%Z /\ (i < j)%Z) ->
  (i = (int.EuclideanDivision.mod1 i j)).

Axiom unicity_div_mod :
  forall (i:Z) (j:Z) (q:Z) (r:Z), (0%Z <= i)%Z -> (0%Z <= q)%Z ->
  (0%Z <= r)%Z -> (0%Z < j)%Z -> (i = ((q * j)%Z + r)%Z) ->
  ((0%Z <= r)%Z /\ (r < j)%Z) ->
  (q = (int.EuclideanDivision.div i j)) /\
  (r = (int.EuclideanDivision.mod1 i j)).

Axiom bound_mod :
  forall (i:Z) (j:Z), (0%Z <= i)%Z -> (0%Z < j)%Z ->
  (0%Z <= (int.EuclideanDivision.mod1 i j))%Z /\
  ((int.EuclideanDivision.mod1 i j) < j)%Z.

Axiom decomp :
  forall (i:Z) (j:Z), (0%Z <= i)%Z -> (0%Z < j)%Z ->
  (i =
   ((j * (int.EuclideanDivision.div i j))%Z +
    (int.EuclideanDivision.mod1 i j))%Z).

Axiom div_plus_quotient :
  forall (i:Z) (j:Z), (0%Z <= i)%Z -> (0%Z < j)%Z ->
  ((int.EuclideanDivision.div (i + j)%Z j) =
   ((int.EuclideanDivision.div i j) + 1%Z)%Z).

Axiom div_plus_fact_gen_div :
  forall (i:Z) (j:Z) (k:Z), (0%Z <= i)%Z -> (0%Z < j)%Z -> (0%Z < k)%Z ->
  ((int.EuclideanDivision.div (i + (k * j)%Z)%Z j) =
   ((int.EuclideanDivision.div i j) + k)%Z).

Axiom mod_plus_fact_gen_mod :
  forall (i:Z) (j:Z) (k:Z), (0%Z <= i)%Z -> (0%Z < j)%Z -> (0%Z <= k)%Z ->
  ((int.EuclideanDivision.mod1 ((k * j)%Z + i)%Z j) =
   (int.EuclideanDivision.mod1 i j)).

Axiom bound_div :
  forall (i:Z) (q:Z) (f2:Z), (0%Z <= i)%Z -> (0%Z <= q)%Z -> (0%Z <= f2)%Z ->
  (i < (f2 * q)%Z)%Z ->
  ((0%Z <= ((int.EuclideanDivision.div i q) * q)%Z)%Z /\
   ((((int.EuclideanDivision.div i q) * q)%Z <= i)%Z /\
    (i < (q * ((int.EuclideanDivision.div i q) + 1%Z)%Z)%Z)%Z)) /\
  ((int.EuclideanDivision.div i q) < f2)%Z.

Axiom mod_invariant :
  forall (i:Z) (q:Z) (f2:Z), (0%Z <= i)%Z -> (0%Z < q)%Z -> (0%Z < f2)%Z ->
  ((int.EuclideanDivision.mod1
    ((q * (f2 * (int.EuclideanDivision.div i (q * f2)%Z))%Z)%Z +
     (int.EuclideanDivision.mod1 i (q * f2)%Z))%Z
    q)
   =
   (int.EuclideanDivision.mod1 (int.EuclideanDivision.mod1 i (q * f2)%Z) q)).

Axiom mod_mod_left :
  forall (i:Z) (j:Z) (f2:Z), (0%Z <= i)%Z -> (0%Z < j)%Z -> (0%Z < f2)%Z ->
  ((int.EuclideanDivision.mod1 (int.EuclideanDivision.mod1 i (f2 * j)%Z) j) =
   (int.EuclideanDivision.mod1 i j)).

Axiom mod_mod_right :
  forall (i:Z) (j:Z) (f2:Z), (0%Z <= i)%Z -> (0%Z < j)%Z -> (0%Z < f2)%Z ->
  ((int.EuclideanDivision.mod1 (int.EuclideanDivision.mod1 i (j * f2)%Z) j) =
   (int.EuclideanDivision.mod1 i j)).

Axiom mod_mod_rev :
  forall (i:Z) (j:Z) (f2:Z), (0%Z <= i)%Z -> (0%Z < j)%Z -> (0%Z < f2)%Z ->
  ((int.EuclideanDivision.mod1 i j) =
   (int.EuclideanDivision.mod1 (int.EuclideanDivision.mod1 i (j * f2)%Z) j)) /\
  ((int.EuclideanDivision.mod1 i j) =
   (int.EuclideanDivision.mod1 (int.EuclideanDivision.mod1 i (f2 * j)%Z) j)).

Axiom mod_mod_plus :
  forall (i:Z) (j:Z), (0%Z <= i)%Z -> (0%Z < j)%Z ->
  ((int.EuclideanDivision.mod1 i j) =
   (int.EuclideanDivision.mod1 (int.EuclideanDivision.mod1 i (j + j)%Z) j)).

Axiom mult_assoc :
  forall (i:Z) (q:Z) (f2:Z), (0%Z <= i)%Z -> (0%Z < q)%Z -> (0%Z < f2)%Z ->
  ((q * (f2 * (int.EuclideanDivision.div i (q * f2)%Z))%Z)%Z =
   ((q * f2)%Z * (int.EuclideanDivision.div i (q * f2)%Z))%Z).

Axiom div_div :
  forall (i:Z) (j:Z) (k:Z), (0%Z <= i)%Z -> (0%Z < j)%Z -> (0%Z < k)%Z ->
  ((int.EuclideanDivision.div (int.EuclideanDivision.div i k) j) =
   (int.EuclideanDivision.div i (k * j)%Z)) /\
  ((int.EuclideanDivision.div (int.EuclideanDivision.div i k) j) =
   (int.EuclideanDivision.div i (j * k)%Z)).

Axiom mod_div :
  forall (i:Z) (j:Z) (k:Z), (0%Z <= i)%Z -> (0%Z < j)%Z -> (0%Z < k)%Z ->
  ((int.EuclideanDivision.div (int.EuclideanDivision.mod1 i (j * k)%Z) j) =
   (int.EuclideanDivision.mod1 (int.EuclideanDivision.div i j) k)).

Axiom inf_mul :
  forall (ia:Z) (ib:Z) (a:Z) (b:Z), ((0%Z <= ia)%Z /\ (ia < a)%Z) ->
  ((0%Z <= ib)%Z /\ (ib < b)%Z) ->
  (((a * ib)%Z + ia)%Z < (a * b)%Z)%Z /\ (((ib * a)%Z + ia)%Z < (b * a)%Z)%Z.

Axiom inf_mul_comm :
  forall (i:Z) (bi:Z) (quot:Z) (rest:Z), ((0%Z <= i)%Z /\ (i < bi)%Z) ->
  (0%Z < rest)%Z -> (0%Z < quot)%Z -> (bi = (quot * rest)%Z) ->
  ((int.EuclideanDivision.div i quot) < rest)%Z /\
  ((int.EuclideanDivision.mod1 i rest) < rest)%Z.

Axiom neutrals :
  (0%Z = (neutral_elt (fun (y0:Z) (y1:Z) => (y0 + y1)%Z))) /\
  (1%Z = (neutral_elt (fun (y0:Z) (y1:Z) => (y0 * y1)%Z))).

(* Why3 assumption *)
Definition isum {a:Type} {a_WT:WhyType a} (s:set a) (t1:a -> Z) : Z :=
  iterate (fun (y0:Z) (y1:Z) => (y0 + y1)%Z) s t1.

Axiom isum_iter : iterates (fun (y0:Z) (y1:Z) => (y0 + y1)%Z) 0%Z.

Axiom isum_iter__ : iterable (fun (y0:Z) (y1:Z) => (y0 + y1)%Z).

Axiom isum_iter_ :
  (opposite_n (fun (y0:Z) (y1:Z) => (y0 + y1)%Z)
   (fun (y0:Z) (y1:Z) => (y0 - y1)%Z) 0%Z) /\
  ((opposite (fun (y0:Z) (y1:Z) => (y0 + y1)%Z)
    (fun (y0:Z) (y1:Z) => (y0 - y1)%Z)) /\
   ((opposite_com (fun (y0:Z) (y1:Z) => (y0 + y1)%Z)
     (fun (y0:Z) (y1:Z) => (y0 - y1)%Z)) /\
    (inverse_tuple (fun (y0:Z) (y1:Z) => (y0 + y1)%Z)
     (fun (y0:Z) (y1:Z) => (y0 - y1)%Z) 0%Z))).

Axiom neutral_zero1 :
  ((neutral_elt (fun (y0:Z) (y1:Z) => (y0 + y1)%Z)) = 0%Z).

(* Why3 assumption *)
Definition ind_isum (f2:Z -> Z) (i:Z) (j:Z) : Z :=
  int_iterate (fun (y0:Z) (y1:Z) => (y0 + y1)%Z) f2 i j.

Axiom isum_to_iterate :
  forall (f2:Z -> Z) (i:Z) (j:Z),
  ((ind_isum f2 i j) =
   (int_iterate (fun (y0:Z) (y1:Z) => (y0 + y1)%Z) f2 i j)).

Axiom ind_isum_plus_one :
  forall (f2:Z -> Z) (i:Z) (j:Z), (i < j)%Z ->
  ((ind_isum f2 i j) = ((f2 i) + (ind_isum f2 (i + 1%Z)%Z j))%Z).

Axiom ind_isum_right_extension :
  forall (f2:Z -> Z) (i:Z) (j:Z), (i <= j)%Z ->
  ((ind_isum f2 i (j + 1%Z)%Z) = ((ind_isum f2 i j) + (f2 j))%Z).

Axiom ind_isum_eq :
  forall (f2:Z -> Z) (g:Z -> Z) (i:Z) (j:Z),
  (forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> ((f2 k) = (g k))) ->
  ((ind_isum f2 i j) = (ind_isum g i j)).

(* Why3 assumption *)
Definition ind_iproduct (f2:Z -> Z) (i:Z) (j:Z) : Z :=
  int_iterate (fun (y0:Z) (y1:Z) => (y0 * y1)%Z) f2 i j.

Axiom ind_iproduct_eq :
  forall (f2:Z -> Z) (g:Z -> Z) (i:Z) (j:Z),
  (forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> ((f2 k) = (g k))) ->
  ((ind_iproduct f2 i j) = (ind_iproduct g i j)).

Axiom iproduct_to_iterate :
  forall (f2:Z -> Z) (i:Z) (j:Z),
  ((ind_iproduct f2 i j) =
   (int_iterate (fun (y0:Z) (y1:Z) => (y0 * y1)%Z) f2 i j)).

Axiom ind_iproduct_empty :
  forall (f2:Z -> Z) (i:Z) (j:Z), (j <= i)%Z -> ((ind_iproduct f2 i j) = 1%Z).

Axiom ind_iproduct_plus_one :
  forall (f2:Z -> Z) (i:Z) (j:Z), (i < j)%Z ->
  ((ind_iproduct f2 i j) = ((f2 i) * (ind_iproduct f2 (i + 1%Z)%Z j))%Z).

Axiom ind_iproduct_right_extension :
  forall (f2:Z -> Z) (i:Z) (j:Z), (i < j)%Z ->
  ((ind_iproduct f2 i j) =
   ((ind_iproduct f2 i (j - 1%Z)%Z) * (f2 (j - 1%Z)%Z))%Z).

Axiom ind_iproduct_right_extension_comm :
  forall (f2:Z -> Z) (i:Z) (j:Z), (i < j)%Z ->
  (((ind_iproduct f2 i (j - 1%Z)%Z) * (f2 (j - 1%Z)%Z))%Z =
   (ind_iproduct f2 i j)).

Axiom positive_iproduct :
  forall (f2:Z -> Z) (i:Z) (j:Z),
  (forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> (0%Z < (f2 k))%Z) ->
  (0%Z < (ind_iproduct f2 i j))%Z.

Axiom ind_iproduct_left_right :
  forall (f2:Z -> Z) (l:Z) (k:Z) (h:Z), ((l <= k)%Z /\ (k <= h)%Z) ->
  ((ind_iproduct f2 l k) =
   (ind_iproduct
    ((((fun (f3:Z -> Z) (l1:Z) (h1:Z) (a:Z) =>
        (f3 ((h1 - (a + 1%Z)%Z)%Z + l1)%Z))
       f2)
      l)
     h)
    ((h - k)%Z + l)%Z h)).

Parameter power: Z -> Z -> Z.

Axiom power_def :
  forall (e:Z) (i:Z), (0%Z <= i)%Z ->
  ((power e i) = (c_iter (fun (y0:Z) (y1:Z) => (y0 * y1)%Z) e i)).

Axiom power_spec :
  forall (e:Z) (i:Z), (0%Z <= i)%Z ->
  ((power e i) =
   (int_iterate (fun (y0:Z) (y1:Z) => (y0 * y1)%Z)
    ((fun (y0:Z) (y1:Z) => y0) e) 0%Z i)).

Axiom power_to_ind_iproduct :
  forall (e:Z) (i:Z), (0%Z <= i)%Z ->
  ((power e i) = (ind_iproduct ((fun (y0:Z) (y1:Z) => y0) e) 0%Z i)).

Axiom power_transl :
  forall (t1:Z) (i:Z) (k:Z), (0%Z <= k)%Z -> (0%Z <= i)%Z ->
  ((power t1 k) =
   (int_iterate (fun (y0:Z) (y1:Z) => (y0 * y1)%Z)
    ((fun (y0:Z) (y1:Z) => y0) t1) i (i + k)%Z)).

Axiom get_power :
  forall (e:Z) (i:Z), (0%Z <= i)%Z ->
  ((power e i) = (c_iter (fun (y0:Z) (y1:Z) => (y0 * y1)%Z) e i)) /\
  ((power e i) = (ind_iproduct ((fun (y0:Z) (y1:Z) => y0) e) 0%Z i)).

Parameter infix_ls_closure: Z -> Z -> bool.

Parameter infix_lseq_closure: Z -> Z -> bool.

Axiom infix_ls_closure_def :
  forall (y:Z) (y1:Z), (((infix_ls_closure y) y1) = true) <-> (y < y1)%Z.

Axiom infix_lseq_closure_def :
  forall (y:Z) (y1:Z), (((infix_lseq_closure y) y1) = true) <-> (y <= y1)%Z.

Axiom pre_cond_int :
  (compat_order_mult infix_ls_closure (fun (y0:Z) (y1:Z) => (y0 * y1)%Z) 0%Z) /\
  ((compat_order_mult infix_lseq_closure (fun (y0:Z) (y1:Z) => (y0 * y1)%Z)
    0%Z) /\
   ((0%Z < 1%Z)%Z /\
    ((partial_order infix_lseq_closure) /\
     ((neutral (fun (y0:Z) (y1:Z) => (y0 * y1)%Z) 1%Z) /\
      ((iterable (fun (y0:Z) (y1:Z) => (y0 * y1)%Z)) /\
       (strict infix_ls_closure infix_lseq_closure)))))).

Axiom power_sum :
  forall (x:Z) (n:Z) (m:Z), (0%Z <= n)%Z -> (0%Z <= m)%Z ->
  ((power x (n + m)%Z) = ((power x n) * (power x m))%Z).

Axiom c_iter_comm1 :
  forall {a:Type} {a_WT:WhyType a},
  forall (op1:a -> a -> a) (x:a) (y:a) (n:Z), (commut op1) -> (0%Z <= n)%Z ->
  (((op1 (c_iter op1 x n)) y) = ((op1 y) (c_iter op1 x n))).

Axiom c_iter_op_comm11 :
  forall (x:Z) (y:Z) (n:Z), (0%Z <= n)%Z ->
  (((power x n) * y)%Z = (y * (power x n))%Z).

Axiom c_iter_op_comm21 :
  forall (x:Z) (y:Z) (n:Z), (0%Z <= n)%Z ->
  ((power (x * y)%Z n) = ((power x n) * (power y n))%Z).

Axiom growing_mult :
  forall (n:Z) (m:Z), (0%Z <= n)%Z -> (1%Z <= m)%Z -> (n <= (n * m)%Z)%Z.

Axiom strict_growing_mult :
  forall (n:Z) (m:Z), (1%Z < n)%Z -> (1%Z < m)%Z -> (n < (n * m)%Z)%Z.

Axiom init_exp :
  forall (k:Z),
  ((power k 0%Z) = 1%Z) /\
  (((power k 1%Z) = k) /\ ((power k 2%Z) = (k * k)%Z)).

Axiom positive_int_exp :
  forall (k:Z) (n:Z), (1%Z <= k)%Z -> (0%Z <= n)%Z ->
  (1%Z <= (power k n))%Z /\
  ((0%Z < (power k n))%Z /\ ((power k n) <= (power k (n + 1%Z)%Z))%Z).

Axiom strict_positive_int_exp :
  forall (k:Z) (n:Z), (1%Z < k)%Z -> (0%Z < n)%Z ->
  (1%Z < (power k n))%Z /\
  (((power k (n - 1%Z)%Z) < (power k n))%Z /\
   ((power k n) < (power k (n + 1%Z)%Z))%Z).

Axiom growing_exp :
  forall (k:Z) (m:Z) (n:Z), (1%Z <= k)%Z -> ((0%Z <= m)%Z /\ (m <= n)%Z) ->
  ((power k m) <= (power k n))%Z.

Axiom strict_growing_exp :
  forall (k:Z) (m:Z) (n:Z), (1%Z < k)%Z -> ((0%Z <= m)%Z /\ (m < n)%Z) ->
  ((power k m) < (power k n))%Z.

Axiom unicity_exp :
  forall (k:Z) (m:Z) (n:Z), (1%Z < k)%Z -> (0%Z <= m)%Z -> (0%Z <= n)%Z ->
  ((power k m) = (power k n)) <-> (m = n).

Axiom bounded_sum_exp :
  forall (i:Z) (j:Z) (k:Z) (m:Z) (n:Z), (0%Z < k)%Z -> (0%Z <= m)%Z ->
  (0%Z <= n)%Z -> (i < (power 2%Z m))%Z -> (j < (power 2%Z n))%Z ->
  (((i * (power 2%Z n))%Z + j)%Z < (power 2%Z (m + n)%Z))%Z.

Axiom int_iterate_def_empty1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (i:Z) (j:Z), (j <= i)%Z ->
  ((int_iterate op1 f2 i j) = (neutral_elt op1)).

Axiom int_iterate_def_plus_one1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (i:Z) (j:Z), (i < j)%Z ->
  ((int_iterate op1 f2 i j) =
   ((op1 (f2 i)) (int_iterate op1 f2 (i + 1%Z)%Z j))).

Axiom int_iterate_def_plus_one_com1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (i:Z) (j:Z), (i < j)%Z ->
  (((op1 (f2 i)) (int_iterate op1 f2 (i + 1%Z)%Z j)) =
   (int_iterate op1 f2 i j)).

Axiom int_iterate_to_iterate1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (i:Z) (j:Z),
  ((int_iterate op1 f2 i j) = (iterate op1 (to_fset i j) f2)).

Axiom int_iterate_right_extension1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (i:Z) (j:Z), (assoc op1) ->
  (i < j)%Z ->
  ((int_iterate op1 f2 i j) =
   ((op1 (int_iterate op1 f2 i (j - 1%Z)%Z)) (f2 (j - 1%Z)%Z))).

Axiom int_iterate_transitivity1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (i:Z) (k:Z) (j:Z), (assoc op1) ->
  (op_neutral_left op1 (neutral_elt op1)) -> ((i <= k)%Z /\ (k <= j)%Z) ->
  ((int_iterate op1 f2 i j) =
   ((op1 (int_iterate op1 f2 i k)) (int_iterate op1 f2 k j))).

Axiom int_iterate_comp_iterate1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (g:Z -> im) (i:Z) (j:Z),
  (assoc op1) -> (op_neutral_right op1 (neutral_elt op1)) -> (commut op1) ->
  ((int_iterate op1
    ((((fun (op2:im -> im -> im) (f3:Z -> im) (g1:Z -> im) (k:Z) =>
        ((op2 (f3 k)) (g1 k)))
       op1)
      f2)
     g)
    i j)
   = ((op1 (int_iterate op1 f2 i j)) (int_iterate op1 g i j))).

Axiom int_iterate_attr_no_f1 :
  forall {im1:Type} {im1_WT:WhyType im1} {im2:Type} {im2_WT:WhyType im2},
  forall (op1:im1 -> im1 -> im1) (op2:im2 -> im2 -> im2) (t1:Z -> im1)
    (t2:Z -> im2) (f2:im1 -> im2) (i:Z) (j:Z),
  (forall (x:Z), forall (y:im1),
   (((op2 (t2 x)) (f2 y)) = (f2 ((op1 (t1 x)) y)))) ->
  ((f2 (neutral_elt op1)) = (neutral_elt op2)) -> (assoc op1) ->
  (assoc op2) -> (forall (i1:Z), ((f2 (t1 i1)) = (t2 i1))) ->
  ((int_iterate op2 t2 i j) = (f2 (int_iterate op1 t1 i j))).

Axiom int_iterate_attr1 :
  forall {im1:Type} {im1_WT:WhyType im1} {im2:Type} {im2_WT:WhyType im2},
  forall (op1:im1 -> im1 -> im1) (op2:im2 -> im2 -> im2) (t1:Z -> im1)
    (f2:im1 -> im2) (i:Z) (j:Z),
  (forall (x:Z), forall (y:im1),
   (((op2 (f2 (t1 x))) (f2 y)) = (f2 ((op1 (t1 x)) y)))) ->
  ((f2 (neutral_elt op1)) = (neutral_elt op2)) -> (assoc op1) ->
  (assoc op2) ->
  ((int_iterate op2
    (((fun (t2:Z -> im1) (f3:im1 -> im2) (e:Z) => (f3 (t2 e))) t1) f2) i j)
   = (f2 (int_iterate op1 t1 i j))).

Axiom int_iterate_attr_comm1 :
  forall {im1:Type} {im1_WT:WhyType im1} {im2:Type} {im2_WT:WhyType im2},
  forall (op1:im1 -> im1 -> im1) (op2:im2 -> im2 -> im2) (t1:Z -> im1)
    (f2:im1 -> im2) (i:Z) (j:Z),
  (forall (x:Z), forall (y:im1),
   (((op2 (f2 (t1 x))) (f2 y)) = (f2 ((op1 (t1 x)) y)))) ->
  ((f2 (neutral_elt op1)) = (neutral_elt op2)) -> (assoc op1) ->
  (assoc op2) ->
  ((f2 (int_iterate op1 t1 i j)) =
   (int_iterate op2
    (((fun (t2:Z -> im1) (f3:im1 -> im2) (e:Z) => (f3 (t2 e))) t1) f2) i j)).

Axiom int_iterate_eq1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (g:Z -> im) (i:Z) (j:Z),
  (forall (k:Z), ((i <= k)%Z /\ (k < j)%Z) -> ((f2 k) = (g k))) ->
  ((int_iterate op1 f2 i j) = (int_iterate op1 g i j)).

Axiom int_iterate_left_right1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (f2:Z -> im) (l:Z) (k:Z) (h:Z), (assoc op1) ->
  (commut op1) -> ((l <= k)%Z /\ (k <= h)%Z) ->
  ((int_iterate op1 f2 l k) =
   (int_iterate op1
    ((((fun (f3:Z -> im) (l1:Z) (h1:Z) (a:Z) =>
        (f3 ((h1 - (a + 1%Z)%Z)%Z + l1)%Z))
       f2)
      l)
     h)
    ((h - k)%Z + l)%Z h)).

Axiom int_iterate_eq_func1 :
  forall {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (i:Z) (j:Z) (f11:Z -> im) (f2:Z -> im),
  (iterable op1) -> (p_injective f11 (to_fset i j)) ->
  (p_injective f2 (to_fset i j)) ->
  ((map f11 (to_fset i j)) = (map f2 (to_fset i j))) ->
  ((int_iterate op1 f11 i j) = (int_iterate op1 f2 i j)).

Axiom int_iterate_map1 :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    {im:Type} {im_WT:WhyType im},
  forall (op1:im -> im -> im) (s:set b) (f2:b -> a) (t1:a -> im),
  (iterable op1) -> (p_injective f2 s) ->
  ((iterate op1 (map f2 s) t1) =
   (iterate op1 s
    (((fun (f3:b -> a) (t2:a -> im) (b1:b) => (t2 (f3 b1))) f2) t1))).

Axiom div_isum_exponents :
  forall (i:Z) (k:Z) (n:Z) (m:Z), (0%Z <= i)%Z -> (0%Z < k)%Z ->
  (0%Z <= n)%Z -> (0%Z <= m)%Z ->
  ((power k (n + m)%Z) = ((power k n) * (power k m))%Z) /\
  (((power k (n + 1%Z)%Z) = ((power k n) * k)%Z) /\
   (((power k 1%Z) = k) /\
    (((int.EuclideanDivision.div (int.EuclideanDivision.div i (power k n))
       (power k m))
      = (int.EuclideanDivision.div i (power k (n + m)%Z))) /\
     ((int.EuclideanDivision.div (int.EuclideanDivision.div i (power k n)) k)
      = (int.EuclideanDivision.div i (power k (n + 1%Z)%Z)))))).

Parameter divp: Z -> Z -> Z.

Axiom divp_def :
  forall (i:Z) (j:Z), (0%Z <= i)%Z -> (0%Z < j)%Z ->
  ((divp i j) = ((int.EuclideanDivision.div i j) * j)%Z).

Axiom divp_spec :
  forall (i:Z) (j:Z), (0%Z <= i)%Z -> (0%Z < j)%Z ->
  (i = ((divp i j) + (int.EuclideanDivision.mod1 i j))%Z) /\
  ((((divp i j) <= i)%Z /\ (i < (((divp i j) + 1%Z)%Z * j)%Z)%Z) /\
   ((j < i)%Z -> (0%Z < (divp i j))%Z)).

Parameter k_th_right: Z -> Z -> Z -> (Z -> Z) -> Z.

Axiom k_th_right_def :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((k_th_right i l h f2) =
   (int.EuclideanDivision.mod1
    (int.EuclideanDivision.div i (ind_iproduct f2 l h)) (f2 h))).

Axiom k_th_right_spec :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  (0%Z <= (k_th_right i l h f2))%Z /\ ((k_th_right i l h f2) < (f2 h))%Z.

Axiom k_th_right_div_mod :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((k_th_right i l h f2) =
   (int.EuclideanDivision.div
    (int.EuclideanDivision.mod1 i (ind_iproduct f2 l (h + 1%Z)%Z))
    (ind_iproduct f2 l h))).

Axiom k_th_right_head_tail :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z),
  ((0%Z <= i)%Z /\ (i < (ind_iproduct f2 l h))%Z) -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((k_th_right i l h f2) =
   (int.EuclideanDivision.div i (ind_iproduct f2 l h))) /\
  ((k_th_right i l l f2) = (int.EuclideanDivision.mod1 i (f2 l))).

Parameter weighted_k_th_right: Z -> Z -> Z -> (Z -> Z) -> Z.

Axiom weighted_k_th_right_def :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((l <= h)%Z ->
   ((weighted_k_th_right i l h f2) =
    ((k_th_right i l h f2) * (ind_iproduct f2 l h))%Z)) /\
  (~ (l <= h)%Z -> ((weighted_k_th_right i l h f2) = 0%Z)).

Axiom weighted_k_th_right_ :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (l <= h)%Z -> (0%Z <= i)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) -> (l < h)%Z ->
  ((int.EuclideanDivision.mod1 i (ind_iproduct f2 l (h + 1%Z)%Z)) =
   ((weighted_k_th_right i l h f2) +
    (int.EuclideanDivision.mod1 i (ind_iproduct f2 l h)))%Z).

Axiom k_th_right_decomposition :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((int.EuclideanDivision.mod1 i (ind_iproduct f2 l h)) =
   (ind_isum
    ((((fun (i1:Z) (l1:Z) (f3:Z -> Z) (a:Z) =>
        (weighted_k_th_right i1 l1 a f3))
       i)
      l)
     f2)
    l h)).

Parameter k_th_left: Z -> Z -> Z -> (Z -> Z) -> Z.

Axiom k_th_left_def :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((k_th_left i l h f2) =
   (int.EuclideanDivision.mod1
    (int.EuclideanDivision.div i (ind_iproduct f2 l h)) (f2 (l - 1%Z)%Z))).

Axiom k_th_left_spec :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  (0%Z <= (k_th_left i l h f2))%Z /\
  ((k_th_left i l h f2) < (f2 (l - 1%Z)%Z))%Z.

Parameter k_th_left_const: Z -> Z -> Z -> Z.

Axiom k_th_left_const_def :
  forall (i:Z) (k:Z) (n:Z), (0%Z <= i)%Z -> (0%Z < n)%Z -> (0%Z < k)%Z ->
  ((k_th_left_const i k n) =
   (int.EuclideanDivision.mod1
    (int.EuclideanDivision.div i (power k (n - 1%Z)%Z)) k)).

Axiom k_th_left_const_spec :
  forall (i:Z) (k:Z) (n:Z), (0%Z <= i)%Z -> (0%Z < n)%Z -> (0%Z < k)%Z ->
  (0%Z <= (k_th_left_const i k n))%Z /\ ((k_th_left_const i k n) < k)%Z.

Axiom k_th_left_const_to_k_th_left :
  forall (i:Z) (k:Z) (n:Z), (0%Z <= i)%Z -> (0%Z < n)%Z -> (0%Z < k)%Z ->
  ((k_th_left_const i k n) =
   (k_th_left i 0%Z (n - 1%Z)%Z ((fun (y0:Z) (y1:Z) => y0) k))).

Axiom k_th_left_right :
  forall (i:Z) (l:Z) (k:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z ->
  ((l <= k)%Z /\ (k <= h)%Z) -> (forall (k1:Z), (0%Z < (f2 k1))%Z) ->
  ((k_th_left i l k f2) =
   (k_th_right i ((h - k)%Z + l)%Z h
    ((((fun (l1:Z) (h1:Z) (f3:Z -> Z) (a:Z) =>
        (f3 ((h1 - (a + 1%Z)%Z)%Z + l1)%Z))
       l)
      h)
     f2))).

Axiom k_th_left_div_mod :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((k_th_left i l h f2) =
   (int.EuclideanDivision.div
    (int.EuclideanDivision.mod1 i (ind_iproduct f2 (l - 1%Z)%Z h))
    (ind_iproduct f2 l h))).

Axiom k_th_left_mod :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  (((((fun (y0:Z) (y1:Z) (y2:Z) (y3:Z -> Z) => (k_th_left y0 y1 y2 y3)) i) l)
    h)
   =
   ((((fun (y0:Z) (y1:Z) (y2:Z) (y3:Z -> Z) => (k_th_left y0 y1 y2 y3))
      (int.EuclideanDivision.mod1 i (ind_iproduct f2 (l - 1%Z)%Z h)))
     l)
    h)).

Axiom k_th_left_head_tail :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z),
  ((0%Z <= i)%Z /\ (i < (ind_iproduct f2 l h))%Z) -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((k_th_left i l h f2) =
   (int.EuclideanDivision.div i (ind_iproduct f2 l h))) /\
  ((k_th_left i h h f2) = (int.EuclideanDivision.mod1 i (f2 (h - 1%Z)%Z))).

Parameter weighted_k_th_left: Z -> Z -> Z -> (Z -> Z) -> Z.

Axiom weighted_k_th_left_def :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((l <= h)%Z ->
   ((weighted_k_th_left i l h f2) =
    ((k_th_left i l h f2) * (ind_iproduct f2 l h))%Z)) /\
  (~ (l <= h)%Z -> ((weighted_k_th_left i l h f2) = 0%Z)).

Axiom weighted_k_th_left_ :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (l <= h)%Z -> (0%Z <= i)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) -> (l < h)%Z ->
  ((int.EuclideanDivision.mod1 i (ind_iproduct f2 (l - 1%Z)%Z h)) =
   ((weighted_k_th_left i l h f2) +
    (int.EuclideanDivision.mod1 i (ind_iproduct f2 l h)))%Z).

Axiom k_th_left_decomposition :
  forall (i:Z) (l:Z) (h:Z) (f2:Z -> Z), (0%Z <= i)%Z -> (l <= h)%Z ->
  (forall (k:Z), (0%Z < (f2 k))%Z) ->
  ((int.EuclideanDivision.mod1 i (ind_iproduct f2 l h)) =
   (ind_isum
    ((((fun (i1:Z) (h1:Z) (f3:Z -> Z) (a:Z) =>
        (weighted_k_th_left i1 a h1 f3))
       i)
      h)
     f2)
    (l + 1%Z)%Z h)).

Parameter kronecker_neutral: Z -> Z -> t.

Axiom kronecker_neutral1 : (kronecker_neutral = (make 1%Z 1%Z tone)).

(* Why3 assumption *)
Definition kronecker (m:Z -> Z -> t) (n:Z -> Z -> t) : Z -> Z -> t :=
  make_f ((rows m) * (rows n))%Z ((columns m) * (columns n))%Z
  (((fun (m1:Z -> Z -> t) (n1:Z -> Z -> t) (i:Z) (j:Z) =>
     (infix_asdt
      ((m1 (int.EuclideanDivision.div i (rows n1)))
       (int.EuclideanDivision.div j (columns n1)))
      ((n1 (int.EuclideanDivision.mod1 i (rows n1)))
       (int.EuclideanDivision.mod1 j (columns n1)))))
    m)
   n).

Axiom kronecker_spec :
  forall (m:Z -> Z -> t) (n:Z -> Z -> t),
  ((rows (kronecker m n)) = ((rows m) * (rows n))%Z) /\
  (((columns (kronecker m n)) = ((columns m) * (columns n))%Z) /\
   forall (i:Z) (j:Z), (valid_index (kronecker m n) i j) ->
   ((((kronecker m n) i) j) =
    (infix_asdt
     ((m (int.EuclideanDivision.div i (rows n)))
      (int.EuclideanDivision.div j (columns n)))
     ((n (int.EuclideanDivision.mod1 i (rows n)))
      (int.EuclideanDivision.mod1 j (columns n)))))).

Axiom kronecker_values :
  forall (m:Z -> Z -> t) (n:Z -> Z -> t) (i:Z) (j:Z),
  (valid_index (kronecker m n) i j) ->
  ((((kronecker m n) i) j) =
   (infix_asdt
    ((m (int.EuclideanDivision.div i (rows n)))
     (int.EuclideanDivision.div j (columns n)))
    ((n (int.EuclideanDivision.mod1 i (rows n)))
     (int.EuclideanDivision.mod1 j (columns n))))).

Axiom kronecker_mod_values :
  forall (m:Z -> Z -> t) (n:Z -> Z -> t) (i:Z) (j:Z),
  (valid_index (kronecker m n) i j) ->
  ((((kronecker m n) i) j) =
   (infix_asdt
    ((m
      (int.EuclideanDivision.div
       (int.EuclideanDivision.mod1 i (rows (kronecker m n))) (rows n)))
     (int.EuclideanDivision.div
      (int.EuclideanDivision.mod1 j (columns (kronecker m n))) (columns n)))
    ((n
      (int.EuclideanDivision.mod1
       (int.EuclideanDivision.mod1 i (rows (kronecker m n))) (rows n)))
     (int.EuclideanDivision.mod1
      (int.EuclideanDivision.mod1 j (columns (kronecker m n))) (columns n))))).

Axiom kronecker_indexes :
  forall (m:Z -> Z -> t) (n:Z -> Z -> t) (i:Z) (j:Z) (k:Z) (l:Z),
  (valid_index m i j) -> (valid_index n k l) ->
  valid_index (kronecker m n) ((i * (rows n))%Z + k)%Z
  ((j * (columns n))%Z + l)%Z.

Axiom kronecker_indexes_com :
  forall (m:Z -> Z -> t) (n:Z -> Z -> t) (i:Z) (j:Z),
  (valid_index (kronecker m n) i j) ->
  (valid_index m (int.EuclideanDivision.div i (rows n))
   (int.EuclideanDivision.div j (columns n))) /\
  (valid_index n (int.EuclideanDivision.mod1 i (rows n))
   (int.EuclideanDivision.mod1 j (columns n))).

Axiom kronecker_assoc_pre :
  forall (m:Z -> Z -> t) (n:Z -> Z -> t) (o:Z -> Z -> t) (i:Z) (j:Z),
  ((0%Z <= i)%Z /\ (i < (((rows m) * (rows n))%Z * (rows o))%Z)%Z) ->
  ((0%Z <= j)%Z /\ (j < (((columns m) * (columns n))%Z * (columns o))%Z)%Z) ->
  ((((kronecker (kronecker m n) o) i) j) =
   (((kronecker m (kronecker n o)) i) j)).

Axiom kronecker_assoc :
  op_assoc (fun (y0:Z -> Z -> t) (y1:Z -> Z -> t) => (kronecker y0 y1)).

Axiom neutral_ :
  forall (m:Z -> Z -> t),
  ((kronecker m kronecker_neutral) = m) /\
  ((kronecker kronecker_neutral m) = m).

Axiom neutral1 :
  (kronecker_neutral =
   (neutral_elt (fun (y0:Z -> Z -> t) (y1:Z -> Z -> t) => (kronecker y0 y1)))) /\
  (has_neutral (fun (y0:Z -> Z -> t) (y1:Z -> Z -> t) => (kronecker y0 y1))).

Axiom kronecker_equal :
  forall (m:Z -> Z -> t) (ml:Z -> Z -> t) (n:Z -> Z -> t) (nl:Z -> Z -> t),
  (equal m ml) -> (equal n nl) -> equal (kronecker m n) (kronecker ml nl).

(* Why3 assumption *)
Definition frows (f2:Z -> Z -> Z -> t) (k:Z) : Z := rows (f2 k).

Axiom frows_spec :
  forall (f2:Z -> Z -> Z -> t) (k:Z), (0%Z < (frows f2 k))%Z.

(* Why3 assumption *)
Definition fcolumns (f2:Z -> Z -> Z -> t) (k:Z) : Z := columns (f2 k).

Axiom fcolumns_spec :
  forall (f2:Z -> Z -> Z -> t) (k:Z), (0%Z < (fcolumns f2 k))%Z.

Axiom const_fcol :
  forall (m:Z -> Z -> t) (k:Z),
  ((fcolumns ((fun (y0:Z -> Z -> t) (y1:Z) => y0) m) k) = (columns m)).

Axiom const_frows :
  forall (m:Z -> Z -> t) (k:Z),
  ((frows ((fun (y0:Z -> Z -> t) (y1:Z) => y0) m) k) = (rows m)).

Parameter k_iter: (Z -> Z -> Z -> t) -> Z -> Z -> Z -> Z -> t.

Axiom k_iter_def :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z), (i <= j)%Z ->
  ((k_iter f2 i j) =
   (int_iterate (fun (y0:Z -> Z -> t) (y1:Z -> Z -> t) => (kronecker y0 y1))
    f2 i j)).

Axiom k_iter_spec :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z), (i <= j)%Z ->
  ((rows (k_iter f2 i j)) =
   (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2) i
    j)) /\
  ((columns (k_iter f2 i j)) =
   (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2)
    i j)).

Axiom k_iter_right_extension :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z), (i < j)%Z ->
  ((k_iter f2 i j) = (kronecker (k_iter f2 i (j - 1%Z)%Z) (f2 (j - 1%Z)%Z))).

Axiom k_iter_left_extension :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z), (i < j)%Z ->
  ((k_iter f2 i j) = (kronecker (f2 i) (k_iter f2 (i + 1%Z)%Z j))).

Parameter k_proj:
  (Z -> Z -> Z -> t) -> (Z -> Z) -> (Z -> Z) -> Z -> Z -> Z -> Z -> t.

Axiom k_proj_def :
  forall (f2:Z -> Z -> Z -> t) (f11:Z -> Z) (f21:Z -> Z) (i:Z) (j:Z) 
    (l:Z) (h:Z),
  (0%Z <= i)%Z -> (0%Z <= j)%Z -> (l < h)%Z ->
  (forall (k:Z), (0%Z < (f11 k))%Z) -> (forall (k:Z), (0%Z < (f21 k))%Z) ->
  ((k_proj f2 f11 f21 i j l h) =
   (((f2 l) (k_th_left i (l + 1%Z)%Z h f11)) (k_th_left j (l + 1%Z)%Z h f21))).

Axiom k_proj_mod :
  forall (f2:Z -> Z -> Z -> t) (f11:Z -> Z) (f21:Z -> Z) (i:Z) (j:Z) 
    (l:Z) (h:Z),
  (0%Z <= i)%Z -> (0%Z <= j)%Z -> (l < h)%Z ->
  (forall (k:Z), (0%Z < (f11 k))%Z) -> (forall (k:Z), (0%Z < (f21 k))%Z) ->
  ((k_proj f2 f11 f21 i j l h) =
   (k_proj f2 f11 f21 (int.EuclideanDivision.mod1 i (ind_iproduct f11 l h))
    (int.EuclideanDivision.mod1 j (ind_iproduct f21 l h)) l h)).

Parameter kronecker_indexed_val: (Z -> Z -> Z -> t) -> Z -> Z -> Z -> Z -> t.

Axiom kronecker_indexed_val_def :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z), (0%Z <= i)%Z ->
  (l < h)%Z -> (0%Z <= j)%Z ->
  ((kronecker_indexed_val f2 i j l h) =
   (k_proj f2 ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
    ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2) i j l h)).

Axiom kronecker_indexed_val_div_mod :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z), (0%Z <= i)%Z ->
  ((l + 1%Z)%Z < h)%Z -> (0%Z <= j)%Z ->
  ((kronecker_indexed_val f2 i j l h) =
   (((f2 l)
     (int.EuclideanDivision.div
      (int.EuclideanDivision.mod1 i
       (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
        l h))
      (rows (k_iter f2 (l + 1%Z)%Z h))))
    (int.EuclideanDivision.div
     (int.EuclideanDivision.mod1 j
      (ind_iproduct
       ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2) l h))
     (columns (k_iter f2 (l + 1%Z)%Z h))))).

Axiom kronecker_indexed_val_k_th_left :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z), (0%Z <= i)%Z ->
  (l < h)%Z -> (0%Z <= j)%Z ->
  ((kronecker_indexed_val f2 i j l h) =
   (((f2 l)
     (k_th_left i (l + 1%Z)%Z h
      ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)))
    (k_th_left j (l + 1%Z)%Z h
     ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2)))).

Axiom kronecker_indexed_val_mod_div :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z), (0%Z <= i)%Z ->
  (l < h)%Z -> (0%Z <= j)%Z ->
  ((kronecker_indexed_val f2 i j l h) =
   (((f2 l)
     (int.EuclideanDivision.mod1
      (int.EuclideanDivision.div i
       (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
        (l + 1%Z)%Z h))
      (frows f2 l)))
    (int.EuclideanDivision.mod1
     (int.EuclideanDivision.div j
      (ind_iproduct
       ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2)
       (l + 1%Z)%Z h))
     (fcolumns f2 l)))).

Axiom k_iter_values_pre :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z), (0%Z <= i)%Z ->
  (0%Z <= j)%Z -> (l < h)%Z ->
  ((((k_iter f2 l h)
     (int.EuclideanDivision.mod1 i
      (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
       l h)))
    (int.EuclideanDivision.mod1 j
     (ind_iproduct
      ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2) l h)))
   =
   (infix_asdt
    (((f2 l)
      (int.EuclideanDivision.div
       (int.EuclideanDivision.mod1 i
        (ind_iproduct
         ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2) l h))
       (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
        (l + 1%Z)%Z h)))
     (int.EuclideanDivision.div
      (int.EuclideanDivision.mod1 j
       (ind_iproduct
        ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2) l h))
      (ind_iproduct
       ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2)
       (l + 1%Z)%Z h)))
    (((k_iter f2 (l + 1%Z)%Z h)
      (int.EuclideanDivision.mod1
       (int.EuclideanDivision.mod1 i
        (ind_iproduct
         ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2) l h))
       (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
        (l + 1%Z)%Z h)))
     (int.EuclideanDivision.mod1
      (int.EuclideanDivision.mod1 j
       (ind_iproduct
        ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2) l h))
      (ind_iproduct
       ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2)
       (l + 1%Z)%Z h))))).

Axiom k_iter_values_bounded :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z), (0%Z <= i)%Z ->
  (0%Z <= j)%Z -> ((l + 1%Z)%Z <= h)%Z ->
  ((((k_iter f2 l h)
     (int.EuclideanDivision.mod1 i
      (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
       l h)))
    (int.EuclideanDivision.mod1 j
     (ind_iproduct
      ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2) l h)))
   =
   (ind_product
    (((((fun (f3:Z -> Z -> Z -> t) (i1:Z) (j1:Z) (h1:Z) (k:Z) =>
         (kronecker_indexed_val f3 i1 j1 k h1))
        f2)
       i)
      j)
     h)
    l h)).

Axiom k_iter_values_bounded_div_mod :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z), (0%Z <= i)%Z ->
  (0%Z <= j)%Z -> ((l + 1%Z)%Z <= h)%Z ->
  ((((k_iter f2 l h)
     (int.EuclideanDivision.mod1 i
      (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2)
       l h)))
    (int.EuclideanDivision.mod1 j
     (ind_iproduct
      ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2) l h)))
   =
   (ind_product
    (((((fun (f3:Z -> Z -> Z -> t) (i1:Z) (j1:Z) (h1:Z) (k:Z) =>
         (((f3 k)
           (int.EuclideanDivision.mod1
            (int.EuclideanDivision.div i1
             (ind_iproduct
              ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f3)
              (k + 1%Z)%Z h1))
            (frows f3 k)))
          (int.EuclideanDivision.mod1
           (int.EuclideanDivision.div j1
            (ind_iproduct
             ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f3)
             (k + 1%Z)%Z h1))
           (fcolumns f3 k))))
        f2)
       i)
      j)
     h)
    l h)).

Axiom k_iter_values :
  forall (f2:Z -> Z -> Z -> t) (i:Z) (j:Z) (l:Z) (h:Z),
  ((0%Z <= i)%Z /\
   (i <
    (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (frows y0 y1)) f2) l
     h))%Z) ->
  ((0%Z <= j)%Z /\
   (j <
    (ind_iproduct ((fun (y0:Z -> Z -> Z -> t) (y1:Z) => (fcolumns y0 y1)) f2)
     l h))%Z) ->
  ((l + 1%Z)%Z <= h)%Z ->
  ((((k_iter f2 l h) i) j) =
   (ind_product
    (((((fun (f3:Z -> Z -> Z -> t) (i1:Z) (j1:Z) (h1:Z) (k:Z) =>
         (kronecker_indexed_val f3 i1 j1 k h1))
        f2)
       i)
      j)
     h)
    l h)).

Parameter pow: (Z -> Z -> t) -> Z -> Z -> Z -> t.

Axiom pow_def :
  forall (m:Z -> Z -> t) (n:Z), (0%Z <= n)%Z ->
  ((pow m n) = (k_iter ((fun (y0:Z -> Z -> t) (y1:Z) => y0) m) 0%Z n)).

Axiom pow_spec :
  forall (m:Z -> Z -> t) (n:Z), (0%Z <= n)%Z ->
  ((rows (pow m n)) = (power (rows m) n)) /\
  (((columns (pow m n)) = (power (columns m) n)) /\
   ((pow m n) =
    (c_iter (fun (y0:Z -> Z -> t) (y1:Z -> Z -> t) => (kronecker y0 y1)) m n))).

Axiom pow_transl :
  forall (m:Z -> Z -> t) (i:Z) (k:Z), (0%Z <= k)%Z -> (0%Z <= i)%Z ->
  ((pow m k) = (k_iter ((fun (y0:Z -> Z -> t) (y1:Z) => y0) m) i (k + i)%Z)).

Axiom pow_plus_one :
  forall (m:Z -> Z -> t) (n:Z), (0%Z < n)%Z ->
  ((pow m n) = (kronecker m (pow m (n - 1%Z)%Z))).

Axiom pow_values_const :
  forall (m:Z -> Z -> t) (i:Z) (j:Z) (n:Z), (0%Z <= i)%Z -> (0%Z <= j)%Z ->
  (0%Z < n)%Z ->
  ((((pow m n) (int.EuclideanDivision.mod1 i (power (rows m) n)))
    (int.EuclideanDivision.mod1 j (power (columns m) n)))
   =
   (ind_product
    (((((fun (m1:Z -> Z -> t) (i1:Z) (j1:Z) (n1:Z) (k:Z) =>
         ((m1
           (int.EuclideanDivision.mod1
            (int.EuclideanDivision.div i1
             (power (rows m1) ((n1 - k)%Z + 1%Z)%Z))
            (rows m1)))
          (int.EuclideanDivision.mod1
           (int.EuclideanDivision.div j1
            (power (columns m1) ((n1 - k)%Z + 1%Z)%Z))
           (columns m1))))
        m)
       i)
      j)
     n)
    0%Z n)).

Parameter m: Z -> Z -> t.

Parameter i: Z.

Parameter j: Z.

Parameter n: Z.

Axiom H : (0%Z <= i)%Z.

Axiom H1 : (0%Z <= j)%Z.

Axiom H2 : (0%Z < n)%Z.

Axiom H3 :
  ((((pow m n) (int.EuclideanDivision.mod1 i (power (rows m) n)))
    (int.EuclideanDivision.mod1 j (power (columns m) n)))
   =
   (ind_product
    (fun (k:Z) =>
     ((m
       (int.EuclideanDivision.mod1
        (int.EuclideanDivision.div i (power (rows m) ((n - k)%Z + 1%Z)%Z))
        (rows m)))
      (int.EuclideanDivision.mod1
       (int.EuclideanDivision.div j (power (columns m) ((n - k)%Z + 1%Z)%Z))
       (columns m))))
    0%Z n)).

Axiom H4 :
  ((((pow m n) (int.EuclideanDivision.mod1 i (power (rows m) n)))
    (int.EuclideanDivision.mod1 j (power (columns m) n)))
   =
   (ind_product
    (fun (k:Z) =>
     ((m (k_th_left_const i (rows m) ((n - k)%Z + 2%Z)%Z))
      (k_th_left_const j (columns m) ((n - k)%Z + 2%Z)%Z)))
    0%Z n)).

Parameter k: Z.

Axiom H5 : (0%Z <= k)%Z.

Axiom H6 : (k < n)%Z.

(* Why3 goal *)
Theorem G :
  (((fun (k1:Z) =>
     ((m
       (k_th_left i 0%Z ((n - k1)%Z + 1%Z)%Z
        ((fun (y0:Z) (y1:Z) => y0) (rows m))))
      (k_th_left j 0%Z ((n - k1)%Z + 1%Z)%Z
       ((fun (y0:Z) (y1:Z) => y0) (columns m)))))
    k)
   =
   ((m
     (k_th_left i 0%Z ((n - k)%Z + 1%Z)%Z
      ((fun (y0:Z) (y1:Z) => y0) (rows m))))
    (k_th_left j 0%Z ((n - k)%Z + 1%Z)%Z
     ((fun (y0:Z) (y1:Z) => y0) (columns m))))).
Proof.
trivial.


Qed.

